import crypto from 'crypto';
import { publicAppUrl, rateLimitStoreConfig } from './config.js';
const buckets = new Map();
export const BODY_LIMIT = '100kb';
export function requestId(req, res, next) { req.requestId = crypto.randomUUID(); res.setHeader('X-Request-Id', req.requestId); next(); }
export function securityHeaders(_req, res, next) { res.removeHeader?.('X-Powered-By'); res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin'); res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=(self)'); res.setHeader('Content-Security-Policy', "default-src 'self'; script-src 'self' 'unsafe-inline' https://accounts.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; connect-src 'self' https://oauth2.googleapis.com https://*.tile.openstreetmap.org; frame-src https://accounts.google.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"); if (process.env.NODE_ENV === 'production') res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains'); next(); }
function requestOrigin(req) { const headers = req.headers || {}; const host = String(headers['x-forwarded-host'] || headers.host || '').split(',')[0].trim(); const protocol = String(headers['x-forwarded-proto'] || req.protocol || (req.socket?.encrypted ? 'https' : 'http')).split(',')[0].trim(); if (!host || !['http', 'https'].includes(protocol)) return ''; try { return new URL(`${protocol}://${host}`).origin; } catch { return ''; } }
export function csrfProtection(req, res, next) { if (!['POST', 'PUT', 'PATCH', 'DELETE'].includes(req.method)) return next(); let expected; try { expected = publicAppUrl() || requestOrigin(req); } catch { return res.status(503).json({ error: 'Service configuration unavailable.' }); } if (!expected && process.env.NODE_ENV !== 'production') return next(); if (!expected) return res.status(403).json({ error: 'Request origin is not allowed.' }); const source = req.headers?.origin || req.headers?.referer; try { if (source && new URL(source).origin === expected) return next(); } catch { /* reject */ } return res.status(403).json({ error: 'Request origin is not allowed.' }); }
const clientKey = (req) => req.socket?.remoteAddress || req.connection?.remoteAddress || 'unknown';
function localRateLimit(key, now, windowMs) {
  const current = buckets.get(key);
  const entry = !current || current.reset <= now
    ? { count: 1, reset: now + windowMs }
    : { ...current, count: current.count + 1 };
  buckets.set(key, entry);
  return entry;
}
export function rateLimit({ name, limit, windowMs }) { return async (req, res, next) => { const key = `${name}:${clientKey(req)}`; const now = Date.now(); let entry; const store = process.env.NODE_ENV === 'production' ? rateLimitStoreConfig() : null; if (store) { try { const reply = await fetch(`${store.url.replace(/\/$/, '')}/pipeline`, { method: 'POST', headers: { Authorization: `Bearer ${store.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify([['INCR', key], ['PEXPIRE', key, windowMs, 'NX'], ['PTTL', key]]) }); if (!reply.ok) throw new Error('store'); const values = await reply.json(); const count = Number(values[0]?.result); const ttl = Number(values[2]?.result); if (!Number.isFinite(count) || count < 1 || !Number.isFinite(ttl) || ttl < 0) throw new Error('store'); entry = { count, reset: now + Math.max(1, ttl) }; } catch { entry = localRateLimit(key, now, windowMs); } } else { entry = localRateLimit(key, now, windowMs); } res.setHeader('RateLimit-Limit', String(limit)); res.setHeader('RateLimit-Remaining', String(Math.max(0, limit - entry.count))); if (entry.count > limit) { res.setHeader('Retry-After', String(Math.max(1, Math.ceil((entry.reset - now) / 1000)))); return res.status(429).json({ error: 'Too many requests. Please try again later.' }); } next(); }; }
export function resetRateLimits() { buckets.clear(); }
export function logError(error, req) { console.error(JSON.stringify({ level: 'error', requestId: req?.requestId, message: error?.name === 'ConfigurationError' ? 'configuration_error' : 'request_failed' })); }
export function runMiddleware(middleware, req, res) { let continued = false; middleware(req, res, () => { continued = true; }); return continued; }
export async function runAsyncMiddleware(middleware, req, res) { let continued = false; await middleware(req, res, () => { continued = true; }); return continued; }
