import React, { useMemo, useState } from 'react';
import { Calendar, ChartBar, CheckCircle, Clock, Gift, Home, IndianRupee, Menu, MessageCircle, Scissors, Shield, Users } from 'lucide-react';
import { clickToChatUrl, defaultTemplates, renderTemplate } from './lib/whatsapp';
import { dateIn, inr, timeIn } from './lib/format';
import { isSupabaseConfigured, supabase } from './lib/supabase';
import './styles.css';

type Role = 'super_admin' | 'owner' | 'staff';
type Status = 'Pending' | 'Confirmed' | 'Arrived' | 'Completed' | 'Cancelled' | 'No-show';
type Service = { id: string; name: string; category: string; price: number; duration: number; active: boolean; description: string };
type Staff = { id: string; name: string; phone: string; role: string; specialization: string; days: string[]; start: string; end: string; active: boolean; services: string[] };
type Customer = { id: string; name: string; mobile: string; whatsapp: string; gender?: string; birthday?: string; notes: string; membership?: string; totalSpending: number; totalVisits: number; favoriteServices: string[] };
type Appointment = { id: string; customerId: string; serviceId: string; staffId: string; date: string; time: string; status: Status; notes?: string; sale?: { amount: number; discount: number; final: number; method: string } };
type Offer = { id: string; name: string; description: string; discountType: 'Percentage' | 'Fixed amount'; amount: number; active: boolean; start: string; end: string };
const today = '2026-08-11';
const salon = { name: 'Zaya Demo Studio', slug: 'salonmate-palakkad', location: 'GB Road, Palakkad', phone: '+919876543210', whatsapp: '+919876543210', owner: 'Anjali Nair' };
const servicesSeed: Service[] = ['Haircut|Hair|350|30','Hair wash|Hair|250|20','Hair coloring|Hair|1800|120','Facial|Facial|1200|60','Cleanup|Skin|650|40','Threading|Threading|120|15','Waxing|Waxing|700|45','Manicure|Nails|600|45','Pedicure|Nails|750|50','Bridal makeup|Makeup|12000|240'].map((row, i) => { const [name, category, price, duration] = row.split('|'); return { id: `svc-${i+1}`, name, category, price: +price, duration: +duration, active: true, description: `${name} service for Kerala salon customers.` }; });
const staffSeed: Staff[] = [
 { id:'st-1', name:'Meera', phone:'9847000001', role:'Hair stylist', specialization:'Hair', days:['Mon','Tue','Wed','Thu','Fri','Sat'], start:'09:00', end:'18:00', active:true, services:['svc-1','svc-2','svc-3'] },
 { id:'st-2', name:'Fathima', phone:'9847000002', role:'Beautician', specialization:'Facial & skin', days:['Mon','Tue','Wed','Thu','Fri','Sat'], start:'10:00', end:'19:00', active:true, services:['svc-4','svc-5','svc-6','svc-7'] },
 { id:'st-3', name:'Latha', phone:'9847000003', role:'Makeup artist', specialization:'Bridal', days:['Tue','Wed','Thu','Fri','Sat','Sun'], start:'08:00', end:'17:00', active:true, services:['svc-8','svc-9','svc-10'] }
];
const customersSeed: Customer[] = Array.from({ length: 12 }, (_, i) => ({ id:`cus-${i+1}`, name:['Priya','Devika','Asha','Nisha','Anu','Riya','Sneha','Lakshmi','Femi','Archa','Maya','Jisha'][i], mobile:`98765${String(40000+i).padStart(5,'0')}`, whatsapp:`9198765${String(40000+i).padStart(5,'0')}`, notes:'Prefers WhatsApp reminders', totalSpending: (i+1)*650, totalVisits: (i % 5) + 1, favoriteServices:['Haircut','Facial'].slice(0,(i%2)+1), membership: i%3===0?'Gold Membership':undefined }));
const apptSeed: Appointment[] = [{id:'ap-1',customerId:'cus-1',serviceId:'svc-1',staffId:'st-1',date:today,time:'10:00',status:'Confirmed'},{id:'ap-2',customerId:'cus-2',serviceId:'svc-4',staffId:'st-2',date:today,time:'11:30',status:'Pending'},{id:'ap-3',customerId:'cus-3',serviceId:'svc-6',staffId:'st-2',date:today,time:'15:00',status:'Completed',sale:{amount:120,discount:0,final:120,method:'UPI'}}];
function Card({children, className=''}:{children:React.ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
function useDemo(){ const [services,setServices]=useState(servicesSeed); const [staff,setStaff]=useState(staffSeed); const [customers,setCustomers]=useState(customersSeed); const [appointments,setAppointments]=useState(apptSeed); const [offers,setOffers]=useState<Offer[]>([{id:'of-1',name:'Onam Glow',description:'15% off facial and cleanup for Palakkad customers',discountType:'Percentage',amount:15,active:true,start:'2026-08-01',end:'2026-09-15'}]); return {services,setServices,staff,setStaff,customers,setCustomers,appointments,setAppointments,offers,setOffers}; }
export default function App(){ const data=useDemo(); const [route,setRoute]=useState(location.pathname.startsWith('/salon/')?'public':'home'); const [role,setRole]=useState<Role>('owner'); const [toast,setToast]=useState(''); const ctx={...data,toast,setToast}; return <><header className="top"><b className="brand"><Scissors/> Zaya</b><nav>{['home','dashboard','appointments','customers','services','staff','offers','sales','membership','settings','admin','public'].map(r=><button key={r} onClick={()=>setRoute(r)}>{r}</button>)}</nav><select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="owner">Owner</option><option value="staff">Staff</option><option value="super_admin">Super Admin</option></select></header>{toast&&<div className="toast">{toast}</div>}<main>{route==='home'?<Marketing setRoute={setRoute}/>:route==='dashboard'?<Dashboard {...ctx} role={role}/>:route==='appointments'?<Appointments {...ctx}/>:route==='customers'?<Customers {...ctx}/>:route==='services'?<Services {...ctx}/>:route==='staff'?<StaffPage {...ctx}/>:route==='offers'?<Offers {...ctx}/>:route==='sales'?<Sales {...ctx}/>:route==='membership'?<Membership/>:route==='settings'?<Settings/>:route==='admin'?<Admin/>:<PublicBooking {...ctx}/>}</main><Bottom setRoute={setRoute}/></> }
function Marketing({setRoute}:{setRoute:(r:string)=>void}){return <div className="hero"><div><p className="pill">Built for Palakkad, Koduvayur, Kollengode & Kinassery salons</p><h1>Run Your Salon. Grow Your Customers.</h1><p>Simple salon booking, customer management and WhatsApp marketing for salons in Kerala.</p><button onClick={()=>setRoute('dashboard')}>Start Free</button><button className="ghost" onClick={()=>setRoute('public')}>Book a Demo</button></div><Card><h2>How it works</h2><ol><li>Customer opens WhatsApp/public page</li><li>Selects service, date and slot</li><li>Salon confirms and sends WhatsApp reminder</li><li>Visit completes and sale/customer history updates</li></ol></Card><Pricing/><FAQ/></div>}
function Dashboard(p:any){ const completed=p.appointments.filter((a:Appointment)=>a.status==='Completed'); const sales=completed.reduce((s:number,a:Appointment)=>s+(a.sale?.final||p.services.find((x:Service)=>x.id===a.serviceId)?.price||0),0); return <><h1>Good morning, {salon.owner}</h1><p>{dateIn(today)}</p><div className="grid stats">{[['Today’s appointments',p.appointments.length,Calendar],['Completed',completed.length,CheckCircle],['Today’s sales',inr(sales),IndianRupee],['New customers',4,Users],['Available staff',p.staff.filter((s:Staff)=>s.active).length,Clock]].map(([l,v,I]:any)=><Card><I/><span>{l}</span><b>{v}</b></Card>)}</div><Appointments {...p} compact/></>}
function Appointments(p:any){ const [form,setForm]=useState({customerId:'cus-1',serviceId:'svc-1',staffId:'st-1',date:today,time:'12:00',notes:''}); const slots=['09:00','09:30','10:00','10:30','11:00','11:30','12:00','15:00','15:30','16:00']; const conflict=p.appointments.some((a:Appointment)=>a.staffId===form.staffId&&a.date===form.date&&a.time===form.time&& !['Cancelled','No-show'].includes(a.status)); const add=()=>{ if(conflict)return p.setToast('Double booking prevented for this staff member.'); p.setAppointments([...p.appointments,{...form,id:crypto.randomUUID(),status:'Pending'}]); p.setToast('Booking created in under 30 seconds.'); }; return <><h2>Today’s Appointments</h2><div className="grid two"><Card><h3>+ New Booking</h3>{['customerId','serviceId','staffId'].map(k=><select value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{(k==='customerId'?p.customers:k==='serviceId'?p.services:p.staff).map((x:any)=><option value={x.id}>{x.name}</option>)}</select>)}<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><select value={form.time} onChange={e=>setForm({...form,time:e.target.value})}>{slots.map(s=><option>{s}</option>)}</select>{conflict&&<p className="error">This staff member is already booked at {timeIn(form.time)}.</p>}<button onClick={add}>Confirm Booking</button></Card><Card>{p.appointments.map((a:Appointment)=><AppointmentRow key={a.id} a={a} p={p}/>)}</Card></div></>}
function AppointmentRow({a,p}:any){ const c=p.customers.find((x:Customer)=>x.id===a.customerId), s=p.services.find((x:Service)=>x.id===a.serviceId), st=p.staff.find((x:Staff)=>x.id===a.staffId); const msg=renderTemplate(defaultTemplates.booking_confirmation,{'Customer Name':c.name,'Salon Name':salon.name,Date:dateIn(a.date),Time:timeIn(a.time),Service:s.name}); return <div className="row"><b>{c.name}</b><span>{s.name} • {st.name} • {timeIn(a.time)}</span><select value={a.status} onChange={e=>p.setAppointments(p.appointments.map((x:Appointment)=>x.id===a.id?{...x,status:e.target.value as Status,sale:e.target.value==='Completed'?{amount:s.price,discount:0,final:s.price,method:'UPI'}:x.sale}:x))}>{['Pending','Confirmed','Arrived','Completed','Cancelled','No-show'].map(x=><option>{x}</option>)}</select><a href={clickToChatUrl(c.whatsapp,msg)} target="_blank">WhatsApp</a></div>}
function Customers(p:any){return <><h2>Customers</h2><div className="grid three">{p.customers.map((c:Customer)=><Card><h3>{c.name}</h3><p>{c.mobile}</p><p>{c.totalVisits} visits • {inr(c.totalSpending)}</p><p>Favorites: {c.favoriteServices.join(', ')}</p><a href={clickToChatUrl(c.whatsapp,`Hi ${c.name}, this is ${salon.name}. How can we help you today?`)}>WhatsApp Customer</a><button>Book Appointment</button></Card>)}</div></>}
function Services(p:any){return <Crud title="Services" items={p.services} fields={['name','category','price','duration','active']}/>}
function StaffPage(p:any){return <Crud title="Staff" items={p.staff} fields={['name','phone','role','specialization','start','end','active']}/>}
function Offers(p:any){return <><h2>Offers</h2><div className="grid two">{p.offers.map((o:Offer)=><Card><Gift/><h3>{o.name}</h3><p>{o.description}</p><p>{o.discountType}: {o.amount}</p><a href={clickToChatUrl(salon.whatsapp,renderTemplate(defaultTemplates.offer,{'Customer Name':'Customer','Salon Name':salon.name,Offer:o.description}))}>Send Offer via WhatsApp</a></Card>)}</div></>}
function Sales(p:any){ const total=p.appointments.reduce((s:number,a:Appointment)=>s+(a.sale?.final||0),0); return <><h2>Sales</h2><div className="grid stats"><Card>Today {inr(total)}</Card><Card>Weekly {inr(total*4)}</Card><Card>Monthly {inr(total*18)}</Card><Card>Average bill {inr(total/Math.max(1,p.appointments.filter((a:Appointment)=>a.sale).length))}</Card></div><ChartBar className="big"/></>}
function Membership(){return <Crud title="Membership plans" items={[{name:'Gold Membership',price:999,benefits:'10% discount, priority booking, birthday offer',status:'Active'}]} fields={['name','price','benefits','status']}/>}
function Settings(){return <><h2>Salon Profile & Onboarding</h2><Card><p>Step 1 Salon name → Step 2 Location → Step 3 WhatsApp → Step 4 Services → Step 5 Staff → Step 6 Working hours → Step 7 Finish</p><progress value="86" max="100"/><Crud title="Profile" items={[salon]} fields={['name','location','phone','whatsapp']}/><p>Supabase Auth: {isSupabaseConfigured?'configured':'add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY'}</p></Card></>}
function Admin(){return <><h2><Shield/> Super Admin</h2><div className="grid stats">{['Total salons 5','Active salons 4','Total customers 100','Appointments this month 200','MRR ₹2,996','New salons this month 2'].map(x=><Card>{x}</Card>)}</div><Pricing/></>}
function PublicBooking(p:any){return <><h1>{salon.name}</h1><p>{salon.location} • Open 9 AM - 7 PM</p><a href={clickToChatUrl(salon.whatsapp,'Hi, I want to book an appointment')}>Book on WhatsApp</a><Appointments {...p}/></>}
function Pricing(){return <div className="grid three"><Card><h3>FREE</h3><b>₹0/month</b><p>50 appointments, 1 staff, basic booking</p></Card><Card><h3>BASIC</h3><b>₹499/month</b><p>Unlimited appointments, 5 staff, offers, WhatsApp tools</p></Card><Card><h3>PRO</h3><b>₹999/month</b><p>Unlimited staff, analytics, memberships, marketing tools</p></Card></div>}
function FAQ(){return <Card><h2>FAQ</h2><p>No customer app required. WhatsApp click-to-chat is used in V1; Business API and Razorpay/Stripe are future integrations.</p></Card>}
function Crud({title,items,fields}:any){return <><h2>{title}</h2><div className="grid three">{items.map((it:any,i:number)=><Card key={i}>{fields.map((f:string)=><p><b>{f}:</b> {String(it[f] ?? '')}</p>)}</Card>)}</div></>}
function Bottom({setRoute}:any){return <footer><button onClick={()=>setRoute('dashboard')}><Home/>Home</button><button onClick={()=>setRoute('appointments')}><Calendar/>Bookings</button><button onClick={()=>setRoute('customers')}><Users/>Customers</button><button onClick={()=>setRoute('settings')}><Menu/>More</button></footer>}
