const root = document.getElementById('root');
const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata' }).format(new Date());
const stateKey = 'salonmate_marketing_mvp_v2';
const oauthStateKey = 'salonmate_google_oauth_state';
const bookingDraftKey = 'salonmate_pending_booking';
const routeForPath = (path = window.location.pathname) => ({
  '/': 'home',
  '/bookings': 'my-bookings',
  '/profile': 'profile',
  '/search': 'explore',
  '/partner/dashboard': 'owner-dashboard',
  '/partner/setup': 'settings'
})[path] || null;
const categories = ['Hair', 'Beauty', 'Bridal', "Men's grooming", "Women's salon", 'Spa'];
const fallbackSalonPhoto = 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80';
const times = ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '14:00', '15:00', '16:00', '17:00'];
function emptyState() {
  return {
    role: 'customer',
    route: 'home',
    activeSalonId: '',
    registeredCustomerId: '',
    salons: [],
    services: [],
    staff: [],
    customers: [],
    bookings: [],
    offers: [],
    campaigns: [],
    redemptions: [],
    notifications: []
  };
}
let db = emptyState();
db.slotHolds ||= [];
db.blockedTimes ||= [];
db.holidays ||= [];
db.ownerNotifications ||= [];
db.settings ||= { cancellationCutoffHours: 2 };
db.accounts ||= [];
let session = null;
let stateRevision = 0;
let loginRole = 'customer';
let authMode = 'signin';
let authNotice = '';
let authModal = null;
let searchQuery = '';
let searchFilter = 'near';
let salonServiceCategory = 'Popular';
let preferredSalonStaff = 'any';
let googleRetryTimer;
let saveTimer;
const persistedAppState = () => { const copy = structuredClone(db); for (const key of ['role', 'route', 'pendingBooking', 'slotHolds', 'activeSalonId', 'activeBookingId', 'registeredCustomerId', 'accounts']) delete copy[key]; return copy; };
const save = () => {
  if (!session) return;
  clearTimeout(saveTimer);
  saveTimer = setTimeout(async () => {
    const response = await fetch('/api/state', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ app: persistedAppState(), revision: stateRevision }) });
    const payload = await response.json().catch(() => ({}));
    if (response.ok) stateRevision = payload.revision;
    else if (response.status === 409) await hydrateDatabase();
  }, 150);
};
async function hydrateDatabase() {
  const response = await fetch('/api/state', { cache: 'no-store' });
  if (!response.ok) return;
  const payload = await response.json();
  if (payload.app && Object.keys(payload.app).length) db = { ...db, ...payload.app };
  stateRevision = payload.revision || 0;
  // Resolve the signed-in customer before rendering a protected route. Without
  // this, loading /bookings directly can render against an unrelated (or
  // missing) customer while the session is still being hydrated.
  if (session?.role === 'customer') ensureSessionCustomer();
  await hydratePublicSalons();
  if (session?.role === 'owner') await hydrateOwnedSalon();
  render();
}
const salon = () => db.salons.find((item) => item.id === db.activeSalonId) || db.salons[0];
const cancellationCutoff = (salonId) => db.salons.find((item) => item.id === salonId)?.cancellationCutoffHours ?? 2;
const bookingRules = (salonId) => { const item = db.salons.find((candidate) => candidate.id === salonId); return { leadHours: item?.bookingLeadTimeHours ?? 2, windowDays: item?.bookingWindowDays ?? 7, confirmationMode: item?.confirmationMode || 'manual' }; };
const addDays = (isoDate, days) => { const date = new Date(`${isoDate}T00:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };
const appointmentTime = (date, time) => new Date(`${date}T${time}:00+05:30`).getTime();
const isBookableDateTime = (salonId, date, time = '23:59') => { const rules = bookingRules(salonId); return date >= today && date <= addDays(today, rules.windowDays) && appointmentTime(date, time) >= Date.now() + rules.leadHours * 3600000; };
const bookingSelectionIsValid = (pending) => Boolean(pending?.time) && isBookableDateTime(pending.salonId, pending.date, pending.time);
function ensureOwnerSalon(account, details = {}) { const existing = db.salons.find((item) => item.accountId === account.accountId || item.ownerId === account.accountId); if (existing) { db.activeSalonId = existing.id; return existing; } const created = { id: `onboarding-${account.accountId}`, accountId: account.accountId, ownerId: account.accountId, name: details.name || '', address: details.location || '', location: details.location || '', phone: '', whatsapp: '', openingHours: '', description: '', featured: false, approved: false, rating: 'New', cancellationCutoffHours: 2, bookingLeadTimeHours: 2, bookingWindowDays: 7, confirmationMode: 'manual' }; db.salons.push(created); db.activeSalonId = created.id; return created; }
const salonFromApi = (item) => ({ id: item.id, accountId: item.ownerId, ownerId: item.ownerId, name: item.salonName || '', phone: item.phone || '', address: item.address || '', location: item.town || '', latitude: item.latitude, longitude: item.longitude, openingHours: item.openingHours || '', whatsapp: item.whatsappNumber || '', description: item.description || '', image: item.image || '', featured: true, approved: item.approvalStatus === 'approved', approvalStatus: item.approvalStatus || 'pending', accountStatus: item.accountStatus || 'inactive', active: item.active === true, rating: 'New', cancellationCutoffHours: 2, bookingLeadTimeHours: item.bookingLeadTimeHours ?? 2, bookingWindowDays: item.bookingWindowDays ?? 7, confirmationMode: item.confirmationMode || 'manual', publicListing: true });
async function hydratePublicSalons() {
  const response = await fetch('/api/state?view=salons', { cache: 'no-store' });
  if (!response.ok) return;
  const { salons = [], services = [], staff = [], offers = [], platformOffers = [] } = await response.json();
  const publicOwnerIds = new Set(salons.map((item) => item.ownerId));
  const existingByOwner = new Map(db.salons.map((item) => [item.ownerId || item.accountId, item]));
  db.salons = db.salons.filter((item) => !item.publicListing && !publicOwnerIds.has(item.ownerId || item.accountId));
  db.salons.push(...salons.map((item) => ({ ...existingByOwner.get(item.ownerId), ...salonFromApi(item) })));
  const publicSalonIds = new Set(salons.map((item) => item.id));
  const mergePublicCatalog = (current, incoming) => [...(current || []).filter((item) => !publicSalonIds.has(item.salonId)), ...incoming];
  db.services = mergePublicCatalog(db.services, services);
  db.staff = mergePublicCatalog(db.staff, staff);
  db.offers = mergePublicCatalog(db.offers, offers);
  db.platformOffers = platformOffers;
}
async function hydrateOwnedSalon() { const response = await fetch('/api/auth/salon', { cache: 'no-store' }); if (!response.ok) return null; const { salon: owned } = await response.json(); db.salons = db.salons.filter((item) => item.accountId !== session.accountId && item.ownerId !== session.accountId); if (!owned) return ensureOwnerSalon(session); const mapped = salonFromApi(owned); db.salons.push(mapped); db.activeSalonId = mapped.id; return mapped; }
const currentCustomer = () => db.customers.find((item) => item.accountId === session?.accountId)
  || db.customers.find((item) => item.email && item.email.toLowerCase() === session?.email?.toLowerCase())
  || db.customers.find((item) => item.id === db.registeredCustomerId)
  || null;
const bookingVisitorId = () => currentCustomer()?.id || 'anonymous-visitor';
function ensureSessionCustomer() {
  if (!session || session.role === 'owner') return null;
  let customer = db.customers.find((item) => item.accountId === session.accountId)
    || db.customers.find((item) => item.email && item.email.toLowerCase() === session.email?.toLowerCase());
  if (!customer) {
    customer = { id: `cus-${session.accountId}`, accountId: session.accountId, name: session.ownerName || session.name || 'Customer', customName: session.ownerName || session.name || '', mobile: '', email: session.email || '', location: 'Palakkad', totalSpend: 0, visits: 0, favoriteSalons: [] };
    db.customers.push(customer);
  } else if (!customer.accountId) {
    customer.accountId = session.accountId;
  }
  db.registeredCustomerId = customer.id;
  return customer;
}
const salonServices = (salonId = db.activeSalonId) => db.services.filter((item) => item.salonId === salonId && item.active);
const fmt = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
const wa = (phone = '', message) => `https://wa.me/${phone.replace(/\D/g, '')}?text=${encodeURIComponent(message)}`;
const card = (html, className = '') => `<section class="card ${className}">${html}</section>`;
const chip = (text) => `<span class="chip">${text}</span>`;
const statusChip = (status) => `<span class="status-pill status-${status.toLowerCase().replace(/[^a-z]+/g, '-')}">${status === 'Pending' ? 'Awaiting salon' : status}</span>`;
const salonPhoto = (salonItem) => salonItem.image?.startsWith('http') || salonItem.image?.startsWith('data:') ? salonItem.image : fallbackSalonPhoto;
const offerDiscount = (offer) => ['Fixed amount', 'fixed'].includes(offer.type) ? `${fmt(offer.discount)} OFF` : `${offer.discount}% OFF`;
const offerIsEligible = (offer) => offer && offer.active !== false && offer.status !== 'rejected' && offer.status !== 'inactive' && offer.approvalStatus !== 'rejected' && offer.approvalStatus !== 'pending' && (!offer.start || offer.start <= today) && (!offer.end || offer.end >= today) && (!offer.usageLimit || (offer.usageCount || 0) < offer.usageLimit);
const availablePlatformOffers = (salonId = db.activeSalonId) => (db.platformOffers || [])
  .filter((offer) => offer.salonId === 'all' || offer.salonId === salonId)
  .map((offer) => ({ ...offer, start: offer.startDate, end: offer.endDate }))
  .filter(offerIsEligible);
const activeSalonOffers = (salonId = db.activeSalonId) => {
  const offers = [
    ...availablePlatformOffers(salonId),
    ...db.offers.filter((offer) => offer.salonId === salonId && offerIsEligible(offer)),
  ];
  return offers.filter((offer, index) => offers.findIndex((candidate) => candidate.id === offer.id) === index);
};
const offerAppliesToService = (offer, service) => !offer?.service || offer.service === service?.id || offer.service.toLowerCase() === service?.name?.toLowerCase();
const offerMinimum = (offer) => Number(offer?.minValue ?? offer?.minPurchase ?? 0);
const offerSaving = (offer, service) => {
  const price = Number(service?.price || 0);
  if (!offer || !offerAppliesToService(offer, service) || price < offerMinimum(offer)) return 0;
  const rawSaving = ['Fixed amount', 'fixed'].includes(offer.type) ? Number(offer.discount || 0) : price * Number(offer.discount || 0) / 100;
  return Math.max(0, Math.min(price, Math.round(rawSaving)));
};
const serviceOffers = (service, includeUnavailable = false) => activeSalonOffers(service?.salonId).filter((offer) => includeUnavailable || offerSaving(offer, service) > 0).sort((a, b) => offerSaving(b, service) - offerSaving(a, service));
const bestServiceOffer = (service) => serviceOffers(service)[0] || null;
const servicePrice = (service, offer = bestServiceOffer(service)) => ({ original: Number(service?.price || 0), saving: offerSaving(offer, service), final: Number(service?.price || 0) - offerSaving(offer, service) });
function servicePriceMarkup(service, offer = bestServiceOffer(service), compact = false) {
  const price = servicePrice(service, offer);
  if (!price.saving) return `<span class="service-price"><strong>${fmt(price.original)}</strong></span>`;
  return `<span class="service-price ${compact ? 'compact' : ''}"><span class="offer-price-pair"><span class="original-price" aria-label="Original price ${fmt(price.original)}">${fmt(price.original)}</span><strong aria-label="Offer price ${fmt(price.final)}">${fmt(price.final)}</strong></span><span class="service-offer-badge">${offerDiscount(offer)}</span></span>`;
}
const titleCase = (value = '') => value.trim().toLowerCase().replace(/(^|[\s'-])\p{L}/gu, (letter) => letter.toUpperCase());
const activeDisplayName = () => titleCase((db.role === 'customer' ? currentCustomer()?.customName : '') || session?.ownerName || currentCustomer()?.name || 'Zaya User');
const initials = (name) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase();
const brandMark = (admin = false) => `<span class="zaya-brand"><img src="/assets/zaya-mark.svg" alt=""><span><strong>Zaya${admin ? ' Admin' : db.route === 'salon-profile' ? ' — Beauty, beautifully booked.' : ''}</strong><small>Beauty, beautifully booked.</small></span></span>`;
const routePaths = { home: '/', explore: '/search', 'my-bookings': '/bookings', profile: '/profile', 'owner-dashboard': '/partner/dashboard', settings: '/partner/setup' };
const navigate = (route) => { db.route = route; if (routePaths[route]) history.pushState({}, '', routePaths[route]); save(); render(); };
const setRole = (role) => { db.role = role; db.route = role === 'owner' ? 'owner-dashboard' : role === 'admin' ? 'admin-dashboard' : 'home'; save(); render(); };
window.navigate = navigate; window.setRole = setRole;
function nav() {
  const routes = !session ? [['home', 'Home'], ['explore', 'Search']] : db.role === 'customer' ? [['home', 'Home'], ['explore', 'Search'], ['my-bookings', 'Bookings'], ['profile', 'Profile']] : db.role === 'owner' ? [['owner-dashboard', 'Dashboard'], ['owner-bookings', 'Bookings'], ['crm', 'Customers'], ['offers', 'Offers'], ['marketing', 'Marketing'], ['settings', 'Salon setup']] : [['admin-dashboard', 'Dashboard'], ['admin-salons', 'Salons'], ['admin-customers', 'Customers'], ['admin-bookings', 'Bookings'], ['admin-campaigns', 'Campaigns']];
  if (!session) return `<header class="top public">${brandMark()}<nav>${routes.map(([key, label]) => `<button class="${db.route === key ? 'active' : ''}" onclick="navigate('${key}')">${label}</button>`).join('')}</nav><button class="header-login" onclick="openUniversalLogin()">Log In</button></header>`;
  const displayName = activeDisplayName();
  const avatar = session.avatarUrl ? `<img class="nav-avatar" src="${session.avatarUrl}" alt="">` : `<span class="nav-avatar">${initials(displayName)}</span>`;
  return `<header class="top ${db.role}">${brandMark()}<nav>${routes.map(([key, label]) => `<button class="${db.route === key ? 'active' : ''}" onclick="navigate('${key}')">${label}</button>`).join('')}</nav><details class="user-menu"><summary>${avatar}<span class="nav-user-name">${displayName}</span><span class="menu-chevron">⌄</span></summary><div class="user-menu-popover"><button onclick="navigate('${db.role === 'customer' ? 'profile' : 'settings'}')"><span>⚙</span> Profile Settings</button><button class="menu-logout" onclick="logout()"><span>↪</span> Log Out</button></div></details></header>`;
}
function authDialog() { if (!authModal) return ''; if (authModal.trigger === 'role_mismatch') return `<div class="auth-overlay"><section class="auth-modal mismatch-modal" role="dialog" aria-modal="true" aria-labelledby="mismatch-title"><button class="modal-close" onclick="closeAuthModal()" aria-label="Close">×</button><div class="mismatch-icon">!</div><h2 id="mismatch-title">Customer account required</h2><p>You are logged in as a Salon Owner. Switch to a customer account to make a booking?</p><div class="actions"><button onclick="switchToCustomerLogin()">Switch account</button><button class="ghost" onclick="closeAuthModal()">Keep owner session</button></div></section></div>`; const contextual = authModal.trigger === 'booking'; const signingUp = authMode === 'signup'; return `<div class="auth-overlay" onclick="if(event.target===this)closeAuthModal()"><section class="auth-modal" role="dialog" aria-modal="true" aria-labelledby="auth-title"><button class="modal-close" onclick="closeAuthModal()" aria-label="Close">×</button><p class="eyebrow">${contextual ? 'Complete your booking' : 'Universal login'}</p><h2 id="auth-title">${signingUp ? 'Create your account' : contextual ? 'Sign in as a Customer' : 'Welcome back'}</h2><p>${contextual ? 'Your booking details are saved. Sign in to continue where you left off.' : 'Choose the account type you want to access.'}</p><div class="auth-mode-tabs"><button class="${!signingUp ? 'active' : ''}" onclick="setAuthMode('signin')">Sign in</button><button class="${signingUp ? 'active' : ''}" onclick="setAuthMode('signup')">Create account</button></div>${authNotice ? `<div class="auth-notice" role="status">${authNotice}</div>` : ''}${contextual ? '<div class="context-role-pill">Customer booking</div>' : roleSelector()}${signingUp ? signupForm() : signinForm()}${contextual ? '' : '<a class="admin-login-link" href="/admin/login">Administrator login →</a>'}</section></div>`; }
window.openUniversalLogin = () => { authModal = { trigger: 'universal', returnRoute: db.route }; authMode = 'signin'; authNotice = ''; loginRole = 'customer'; render(); };
window.closeAuthModal = () => { authModal = null; authNotice = ''; render(); };
window.switchToCustomerLogin = async () => { await fetch('/api/auth/logout', { method: 'POST' }); session = null; db.role = 'customer'; loginRole = 'customer'; authModal = { trigger: 'booking', returnRoute: 'book' }; authMode = 'signin'; render(); };
function roleSelector() { return `<fieldset class="role-segment auth-role-cards"><legend>Choose your role</legend><button type="button" class="${loginRole === 'customer' ? 'active' : ''}" onclick="setLoginRole('customer')"><b>Customer</b><small>Find and book salons</small></button><button type="button" class="${loginRole === 'salon_owner' ? 'active' : ''}" onclick="setLoginRole('salon_owner')"><b>Salon Owner</b><small>Manage your salon</small></button></fieldset>`; }
function googleButton() { return `<div id="home-google-signin" class="google-auth-mount"><span>Loading Google Sign-In…</span></div><p id="home-google-status" class="oauth-status" role="status"></p><p class="oauth-disclaimer">By continuing, you agree to Zaya's Terms and Privacy Policy.</p>`; }
function signinForm() { return `<div>${googleButton()}<div class="auth-divider"><span>or sign in with email</span></div><form onsubmit="manualSignIn(event)"><label>Email address<input id="signin-email" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Password<input id="signin-password" type="password" autocomplete="current-password" minlength="8" required placeholder="Enter your password"></label><div class="signin-options"><span></span><button type="button" onclick="forgotPassword()">Forgot Password?</button></div><button class="full-button" type="submit">Sign In</button><p id="signin-error" class="error" role="alert"></p></form></div>`; }
function signupForm() { const owner = loginRole === 'salon_owner'; return `<div>${googleButton()}<div class="auth-divider"><span>or sign up with email</span></div><form onsubmit="submitSignup(event)"><label>Full name<input id="signup-name" autocomplete="name" required placeholder="Your full name"></label><label>Email address<input id="signup-email" type="email" autocomplete="email" required placeholder="you@example.com"></label>${owner ? `<div class="form-grid"><label>Salon name<input id="signup-salon" required placeholder="Your salon name"></label><label>Location<input id="signup-location" required placeholder="Palakkad"></label></div>` : ''}<label>Password<input id="signup-password" type="password" autocomplete="new-password" minlength="8" required placeholder="At least 8 characters"></label><label class="terms-check"><input id="signup-terms" type="checkbox" required> I agree to the Terms and Privacy Policy</label><button class="full-button" type="submit">${owner ? 'Create salon account' : 'Create customer account'}</button><p id="signup-error" class="error" role="alert"></p></form></div>`; }
window.setAuthMode = (mode) => { authMode = mode; authNotice = ''; render(); };
window.setLoginRole = (role) => { loginRole = role; authNotice = ''; render(); };
const normalizeEmail = (email) => email.trim().toLowerCase();
async function completeAuthentication(nextSession, shouldHydrate = true) { const loginContext = authModal; const claims = new Set((nextSession.roles || []).map((role) => role.toUpperCase())); if (claims.has('ADMIN') || claims.has('ROLE_ADMIN')) { window.location.assign('/admin/dashboard'); return; } const pending = JSON.parse(sessionStorage.getItem(bookingDraftKey) || 'null'); session = nextSession; if (shouldHydrate) await hydrateDatabase(); if (pending) { if (nextSession.role !== 'customer') { authModal = { trigger: 'role_mismatch' }; db.role = 'owner'; render(); return; } ensureSessionCustomer(); db.pendingBooking = pending; db.activeSalonId = pending.salonId; db.role = 'customer'; db.route = 'book'; authModal = null; render(); await submitBookingRequest(pending); return; } authModal = null; if (nextSession.role === 'owner') { db.role = 'owner'; const ownedSalon = ensureOwnerSalon(nextSession); db.route = ownedSalon.name ? 'owner-dashboard' : 'settings'; history.replaceState({}, '', ownedSalon.name ? '/partner/dashboard' : '/partner/setup'); } else { db.role = 'customer'; ensureSessionCustomer(); db.route = loginContext?.returnRoute || (db.route === 'home' || db.route === 'explore' || db.route === 'salon-profile' ? db.route : 'my-bookings'); } save(); render(); }
async function handleHomeGoogleSignIn(response) { try { if (!response?.credential) throw new Error('Missing Google credential'); const oauthState = JSON.parse(sessionStorage.getItem(oauthStateKey) || 'null'); if (!oauthState || !['customer', 'salon_owner'].includes(oauthState.selectedRole)) throw new Error('Invalid OAuth role'); const result = await fetch('/api/auth/google', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ credential:response.credential, role:oauthState.selectedRole }) }); const account=await result.json(); if(!result.ok) throw new Error(account.error); sessionStorage.removeItem(oauthStateKey); completeAuthentication(account); } catch (error) { text('home-google-status', error.message || 'Google sign-in could not be completed. Please try again.'); } }
function initializeHomeGoogleLogin(attempt = 0) { clearTimeout(googleRetryTimer); const mount = document.getElementById('home-google-signin'); if (!mount) return; const clientId = window.SALONMATE_CONFIG?.googleOAuthClientId || ''; if (!clientId) { mount.innerHTML = '<span>Google Sign-In is not configured.</span>'; return; } if (!window.google?.accounts?.id) { if (attempt < 20) googleRetryTimer = setTimeout(() => initializeHomeGoogleLogin(attempt + 1), 250); else mount.innerHTML = '<span>Google Sign-In failed to load. Refresh and try again.</span>'; return; } const oauthState = { selectedRole: loginRole, nonce: crypto.randomUUID() }; sessionStorage.setItem(oauthStateKey, JSON.stringify(oauthState)); window.google.accounts.id.initialize({ client_id: clientId, callback: handleHomeGoogleSignIn, auto_select: false }); mount.innerHTML = ''; window.google.accounts.id.renderButton(mount, { theme: 'outline', size: 'large', text: 'continue_with', shape: 'pill', width: Math.min(400, Math.max(240, mount.clientWidth)) }); }
window.submitSignup = async (event) => { event.preventDefault(); const name = titleCase(val('signup-name')); const salonName = val('signup-salon').trim(); const salonLocation = val('signup-location').trim(); if (loginRole === 'salon_owner' && (!salonName || !salonLocation)) return text('signup-error', 'Salon name and location are required for salon owners.'); const response = await fetch('/api/auth/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email: normalizeEmail(val('signup-email')), password: val('signup-password'), role: loginRole }) }); const account = await response.json(); if (!response.ok) return text('signup-error', account.error || 'Unable to create account.'); session = account; await hydrateDatabase(); if (account.role === 'customer') { const customer = { id: `cus-${Date.now()}`, accountId: account.accountId, name, customName: name, mobile: '', email: account.email, location: 'Palakkad', totalSpend: 0, visits: 0, favoriteSalons: [] }; db.customers.push(customer); db.registeredCustomerId = customer.id; } else { const salonResponse = await fetch('/api/auth/salon', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ salonName, town: salonLocation }) }); const salonPayload = await salonResponse.json(); if (!salonResponse.ok) return text('signup-error', salonPayload.error || 'Unable to create salon.'); const owned = salonFromApi(salonPayload.salon); db.salons.push(owned); db.activeSalonId = owned.id; } await completeAuthentication(account, false); save(); };
window.manualSignIn = async (event) => { event.preventDefault(); const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: normalizeEmail(val('signin-email')), password: val('signin-password'), role: loginRole }) }); const account = await response.json(); if (!response.ok) return text('signin-error', account.error || 'Unable to sign in.'); completeAuthentication(account); };
window.forgotPassword = () => { authNotice = 'Password recovery instructions will be sent if an account exists for that email.'; render(); };
window.logout = async () => { await fetch('/api/auth/logout', { method: 'POST' }); session = null; db.role = 'customer'; db.route = 'home'; await hydratePublicSalons(); render(); };
function customerHome() {
  const featured = db.salons.filter((item) => item.featured && salonAcceptsBookings(item));
  const featuredOffer = (db.platformOffers || []).map((offer) => ({ ...offer, start: offer.startDate, end: offer.endDate })).find(offerIsEligible)
    || db.offers.find(offerIsEligible);
  const offerSalon = featuredOffer?.salonId === 'all' ? null : db.salons.find((item) => item.id === featuredOffer?.salonId);
  return `<div class="discovery-home">
    <form class="search-bar" onsubmit="event.preventDefault();navigate('explore')"><span class="search-icon">⌕</span><input aria-label="Search salons and services" placeholder="Search salons or location" readonly><button type="submit">Search</button></form>
    ${db.appBanner ? `<div class="app-banner">${db.appBanner}</div>` : ''}
    ${featuredOffer ? `<section class="home-offer"><div><p class="eyebrow">Limited-time offer</p><h2>${featuredOffer.title}</h2>${featuredOffer.description ? `<p>${featuredOffer.description}</p>` : ''}<p><strong>${offerDiscount(featuredOffer)}</strong>${featuredOffer.end ? ` · Valid until ${featuredOffer.end}` : ''}${featuredOffer.minValue ? ` · Minimum booking ${fmt(featuredOffer.minValue)}` : ''}</p></div><button onclick="${offerSalon ? `startSalonBooking('${offerSalon.id}')` : "navigate('explore')"}">${offerSalon ? `Book at ${offerSalon.name}` : 'Find a salon'}</button></section>` : ''}
    <div class="section-title"><h2>Recommended</h2><button onclick="navigate('explore')">See all</button></div>
    <div class="salon-carousel">${featured.map(discoverySalonCard).join('') || card('<div class="empty-state"><b>No salons are available yet</b><p>Approved salons will appear here when they join Zaya.</p></div>')}</div>
    ${db.salons.some(salonAcceptsBookings) ? `<div class="section-title"><h2>Recently viewed</h2></div><div class="salon-carousel compact">${db.salons.filter(salonAcceptsBookings).slice(1, 4).map(discoverySalonCard).join('')}</div>` : ''}
  </div>`;
}
function discoverySalonCard(s) { const service = salonServices(s.id)[0]; const offer = db.offers.find((item) => item.salonId === s.id && offerIsEligible(item)); return `<article class="discovery-card" onclick="openSalon('${s.id}')" tabindex="0"><div class="discovery-photo"><img src="${salonPhoto(s)}" alt="${s.name} salon" loading="lazy" onerror="this.onerror=null;this.src='${fallbackSalonPhoto}'"><span class="rating-badge">★ ${s.rating}</span>${offer ? `<span class="discount-badge">${offerDiscount(offer)}</span>` : ''}</div><div class="discovery-info"><div><h3>${s.name} <i>✓</i></h3><p>${s.address}</p><p>${service?.category || 'Beauty'} · Starts ${fmt(service?.price || 0)}</p></div></div></article>`; }
function register() { const c = currentCustomer(); return `<div class="page-heading"><div><p class="eyebrow">Profile settings</p><h1>Edit your profile</h1><p>Your custom display name overrides your Google account name.</p></div></div>${card(`<label>Preferred display name<input id="reg-name" value="${c.customName || ''}" placeholder="${activeDisplayName()}"></label><label>Mobile number<input id="reg-mobile" value="${c.mobile}"></label><label>Email<input id="reg-email" value="${c.email || session?.email || ''}" readonly></label><label>Date of birth optional<input id="reg-dob" type="date" value="${c.dob || ''}"></label><label>Gender<select id="reg-gender"><option ${c.gender === 'Female' ? 'selected' : ''}>Female</option><option ${c.gender === 'Male' ? 'selected' : ''}>Male</option><option>Prefer not to say</option></select></label><label>Location<input id="reg-location" value="${c.location}"></label><label>Preferred language<select id="reg-language"><option ${c.language === 'English' ? 'selected' : ''}>English</option><option ${c.language === 'Malayalam' ? 'selected' : ''}>Malayalam</option></select></label><div class="actions"><button onclick="saveRegistration()">Save changes</button><button class="ghost" onclick="navigate('profile')">Cancel</button></div>`)}`; }
window.saveRegistration = () => { const c = currentCustomer(); Object.assign(c, { customName: titleCase(val('reg-name')), mobile: val('reg-mobile'), email: val('reg-email'), dob: val('reg-dob'), gender: val('reg-gender'), location: val('reg-location'), language: val('reg-language') }); save(); navigate('profile'); };
const salonAcceptsBookings = (salonItem) => salonItem && salonItem.approved !== false && salonItem.approvalStatus !== 'pending' && salonItem.approvalStatus !== 'rejected' && salonItem.accountStatus !== 'suspended' && salonItem.active !== false && !salonItem.suspended;
function explore() { let list = db.salons.filter((item) => salonAcceptsBookings(item) && matchesSearch(item)); if (searchFilter === 'near') list = list.filter((s) => parseFloat(s.distance) <= 10); if (searchFilter === 'rated') list = list.filter((s) => Number(s.rating) >= 4.5); if (searchFilter === 'open') list = list.filter((s) => salonAcceptsBookings(s)); if (searchFilter === 'price') list.sort((a, b) => startingPrice(a.id) - startingPrice(b.id)); return `<div class="search-heading"><div><p class="eyebrow">Discover</p><h1>Find a salon</h1></div><label class="search-field"><span>⌕</span><input id="search" placeholder="Search salon, location or service" oninput="updateSearch(this.value)" value="${searchQuery}"></label></div><div class="filter-strip" aria-label="Salon filters">${[['near','Near Me'],['rated','Top Rated ★4.5+'],['open','Open Now'],['price','Price: Low to High']].map(([id,label]) => `<button class="filter-chip ${searchFilter === id ? 'active' : ''}" onclick="setSearchFilter('${id}')">${label}</button>`).join('')}</div>${salonList('', list)}`; }
function startingPrice(salonId) { const prices = salonServices(salonId).map((service) => service.price); return prices.length ? Math.min(...prices) : 0; }
function matchesSearch(s) { const q = searchQuery.trim().toLowerCase(); const services = salonServices(s.id).map((item) => item.name).join(' '); return !q || `${s.name} ${s.location} ${s.address} ${services}`.toLowerCase().includes(q); }
window.updateSearch = (query) => { searchQuery = query; render(); requestAnimationFrame(() => { const input = document.getElementById('search'); input?.focus(); input?.setSelectionRange(query.length, query.length); }); };
window.setSearchFilter = (filter) => { searchFilter = filter; render(); };
function salonList(title, list) { return `${title ? `<h2>${title}</h2>` : ''}<div class="grid three salon-grid">${list.map((s) => { const start = startingPrice(s.id); const offer = db.offers.find((item) => item.salonId === s.id && offerIsEligible(item)); return card(`<div class="salon-card-photo"><img src="${salonPhoto(s)}" alt="${s.name} salon" loading="lazy" onerror="this.onerror=null;this.src='${fallbackSalonPhoto}'"><span class="rating-badge">★ ${s.rating}</span>${offer ? `<span class="discount-badge">${offerDiscount(offer)}</span>` : ''}</div><div class="salon-card-body"><h3>${s.name}</h3><p>${s.location} · ${s.distance}</p><div class="price-row"><span>From <strong>${fmt(start)}</strong></span>${offer ? `<span class="offer-tag">${offer.title}</span>` : ''}</div><div class="actions"><button onclick="startSalonBooking('${s.id}')">Book Now</button><button class="ghost" onclick="favoriteSalon('${s.id}')">♡ Favorite</button></div></div>`, 'salon-result-card'); }).join('') || card('<div class="empty-state"><b>No salons found</b><p>Try another search or filter.</p></div>')}</div>`; }
window.openSalon = (id) => { db.activeSalonId = id; db.route = 'salon-profile'; save(); render(); };
window.favoriteSalon = (id) => { const c = currentCustomer(); if (!c.favoriteSalons.includes(id)) c.favoriteSalons.push(id); save(); render(); };
const uiIcon = (name) => ({ location: '<path d="M12 21s6-5.1 6-11a6 6 0 1 0-12 0c0 5.9 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/>', call: '<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.2-1.2a2 2 0 0 1 2.1-.5c1 .3 1.9.6 2.9.7a2 2 0 0 1 1.7 2Z"/>', share: '<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/>', wifi: '<path d="M5 12.6a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0"/><circle cx="12" cy="20" r="1"/>', parking: '<path d="M7 21V3h6a5 5 0 0 1 0 10H7"/>', card: '<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/>', access: '<circle cx="12" cy="4" r="2"/><path d="M10 22v-7l-2-2 2-5 5 3h3M6 18a4 4 0 1 0 7 3"/>', snow: '<path d="M12 2v20M4.2 6.5l15.6 11M4.2 17.5l15.6-11M8 4l4 3 4-3M8 20l4-3 4 3"/>', users: '<circle cx="9" cy="8" r="4"/><path d="M2 21a7 7 0 0 1 14 0M16 4a4 4 0 0 1 0 8M18 14a6 6 0 0 1 4 6"/>' }[name] || '<circle cx="12" cy="12" r="9"/>');
const icon = (name) => `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${uiIcon(name)}</svg>`;
const enabledFacilities = (s) => { const source = s.facilities || s.amenities || []; const configured = Array.isArray(source) ? source : Object.entries(source).filter(([, enabled]) => enabled).map(([name]) => name); const aliases = { ac: ['snow', 'A/C'], 'a/c': ['snow', 'A/C'], wifi: ['wifi', 'Wi-Fi'], 'wi-fi': ['wifi', 'Wi-Fi'], parking: ['parking', 'Parking'], unisex: ['users', 'Unisex'], card: ['card', 'Card payment'], 'card payment': ['card', 'Card payment'], wheelchair: ['access', 'Wheelchair access'], 'wheelchair access': ['access', 'Wheelchair access'] }; return configured.map((item) => aliases[String(item).toLowerCase()]).filter(Boolean); };
function salonProfile() {
  const s = salon();
  if (!s) return '<section class="salon-not-found"><h1>Salon not found</h1><p>This salon may no longer be available.</p><button onclick="navigate(\'explore\')">Browse salons</button></section>';
  const services = salonServices(s.id); const staff = db.staff.filter((p) => p.salonId === s.id); const offers = activeSalonOffers(s.id); const facilities = enabledFacilities(s);
  const categories = ['Popular', ...new Set(services.map((item) => item.category).filter(Boolean))];
  if (!categories.includes(salonServiceCategory)) salonServiceCategory = 'Popular';
  const visibleServices = salonServiceCategory === 'Popular' ? [...services].sort((a, b) => Number(b.popular || b.featured) - Number(a.popular || a.featured)) : services.filter((item) => item.category === salonServiceCategory);
  const rating = s.rating && s.rating !== 'New' ? `<span class="salon-rating">★ ${s.rating}${s.reviewCount ? ` <small>(${s.reviewCount} reviews)</small>` : ''}</span>` : '';
  return `<article class="salon-detail">
    <section class="salon-hero"><div class="salon-image-skeleton"></div><img src="${salonPhoto(s)}" alt="Interior of ${s.name}" onload="this.parentElement.classList.add('loaded')" onerror="this.onerror=null;this.src='${fallbackSalonPhoto}';this.parentElement.classList.add('loaded')"><span class="best-seller">⭐ Best Seller</span></section>
    <section class="salon-summary"><div class="salon-summary-copy"><h1>${s.name}</h1><p>${icon('location')} ${s.location || s.address}</p>${rating}</div>${services.length ? '<button class="book-now" onclick="scrollToSalonServices()">Book Now</button>' : ''}</section>
    ${s.description ? `<p class="salon-description">${s.description}</p>` : ''}
    <nav class="quick-actions" aria-label="Salon contact actions"><a href="tel:${s.phone || ''}" aria-label="Call ${s.name}">${icon('call')}<span>Call</span></a><a href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(Number.isFinite(s.latitude) && Number.isFinite(s.longitude) ? `${s.latitude},${s.longitude}` : s.address || s.location)}" target="_blank" rel="noopener" aria-label="Get directions to ${s.name}">${icon('location')}<span>Directions</span></a><button onclick="shareSalon('${s.id}')" aria-label="Share ${s.name}">${icon('share')}<span>Share</span></button></nav>
    ${facilities.length ? `<section class="salon-section facilities"><h2>FACILITIES AVAILABLE</h2><div class="horizontal-strip">${facilities.map(([symbol, label]) => `<span class="facility-chip">${icon(symbol)}${label}</span>`).join('')}</div></section>` : ''}
    <section class="salon-section services-section" id="salon-services"><h2>Services</h2><div class="service-tabs" role="tablist" aria-label="Service categories">${categories.map((category) => `<button role="tab" aria-selected="${category === salonServiceCategory}" class="${category === salonServiceCategory ? 'active' : ''}" onclick="selectSalonCategory('${category.replace(/'/g, "\\'")}')">${category}</button>`).join('')}</div><div class="profile-service-grid">${visibleServices.map((service) => { const offer = bestServiceOffer(service); return `<article class="profile-service-card"><div><h3>${service.name}</h3><p>${service.description || service.category || 'Salon service'}</p><span class="duration">◷ ${service.duration} min</span>${servicePriceMarkup(service, offer)}</div><button onclick="bookProfileService('${service.id}')" aria-label="Book ${service.name}">Book</button></article>`; }).join('') || '<p class="empty-state-inline">No services available in this category.</p>'}</div></section>
    <section class="salon-section"><h2>Our Staff</h2>${staff.length ? `<div class="staff-carousel"><button class="staff-item ${preferredSalonStaff === 'any' ? 'selected' : ''}" onclick="selectPreferredStaff('any')"><span class="staff-avatar any">Any</span><b>Any staff</b><small>First available</small></button>${staff.map((person) => `<button class="staff-item ${preferredSalonStaff === person.id ? 'selected' : ''}" onclick="selectPreferredStaff('${person.id}')">${person.image ? `<img class="staff-avatar" src="${person.image}" alt="${person.name}" onerror="this.outerHTML='<span class=\'staff-avatar\'>${initials(person.name)}</span>'">` : `<span class="staff-avatar">${initials(person.name)}</span>`}<b>${person.name}</b><small>${person.specialization || person.title || 'Professional'}</small>${person.rating ? `<em>★ ${person.rating}</em>` : ''}</button>`).join('')}</div>` : '<p class="empty-state-inline">No staff details are available yet. You can still book the first available professional.</p>'}</section>
    <section class="salon-section offers-section"><h2>Offers</h2>${offers.length ? `<div class="offer-carousel">${offers.map((offer, index) => `<article class="profile-offer offer-${index % 4}"><span>${offerDiscount(offer)}</span><h3>${offer.title}</h3><p>${offer.description || offer.terms || 'Save on your next salon booking.'}</p>${offer.code ? `<code>${offer.code}</code>` : ''}${offer.end ? `<small>Valid until ${offer.end}</small>` : ''}<button onclick="applyProfileOffer('${offer.id}')">Apply Offer</button></article>`).join('')}</div>` : '<p class="empty-state-inline">No offers available right now.</p>'}</section>
  </article>`;
}
window.scrollToSalonServices = () => document.getElementById('salon-services')?.scrollIntoView({ behavior: 'smooth', block: 'start' });
window.selectSalonCategory = (category) => { salonServiceCategory = category; render(); setTimeout(() => document.getElementById('salon-services')?.scrollIntoView({ block: 'start' }), 0); };
window.selectPreferredStaff = (staffId) => { preferredSalonStaff = staffId; document.querySelectorAll('.staff-item').forEach((item) => item.classList.toggle('selected', item.getAttribute('onclick')?.includes(`'${staffId}'`))); };
window.bookProfileService = (serviceId) => startBooking(serviceId, { staffId: preferredSalonStaff });
window.shareSalon = async () => { const data = { title: `${salon().name} on Zaya`, text: `Book ${salon().name} on Zaya`, url: window.location.href }; if (navigator.share) { try { await navigator.share(data); return; } catch (error) { if (error.name === 'AbortError') return; } } await navigator.clipboard.writeText(data.url); showSalonToast('Link copied'); };
window.showSalonToast = (message) => { document.querySelector('.salon-toast')?.remove(); const toast = document.createElement('div'); toast.className = 'salon-toast'; toast.setAttribute('role', 'status'); toast.textContent = message; document.body.append(toast); setTimeout(() => toast.remove(), 2400); };
window.applyProfileOffer = (offerId) => { const service = salonServices().find((item) => offerSaving(activeSalonOffers().find((offer) => offer.id === offerId), item) > 0); if (!service) return showSalonToast('Offer is not eligible for available services'); startBooking(service.id, { staffId: preferredSalonStaff }); db.pendingBooking.offerId = offerId; db.pendingBooking.offerSelectionInitialized = true; sessionStorage.setItem(bookingDraftKey, JSON.stringify(db.pendingBooking)); render(); };
window.startSalonBooking = (salonId) => { const salonItem = db.salons.find((item) => item.id === salonId); if (!salonAcceptsBookings(salonItem)) return alert('This salon is not accepting new bookings.'); db.activeSalonId = salonId; startBooking(salonServices(salonId)[0]?.id); };
window.startBooking = (serviceId = '', selection = {}) => { const selectedSalonId = selection.salonId || db.activeSalonId; if (!salonAcceptsBookings(db.salons.find((item) => item.id === selectedSalonId))) return alert('This salon is not accepting new bookings.'); const draft = { salonId: selectedSalonId, serviceId: serviceId || selection.serviceId || salonServices(selectedSalonId)[0]?.id, staffId: selection.staffId || 'any', date: selection.date || today, time: selection.time || '', forWhom: selection.forWhom || 'self', walkIn: false, step: 1 }; db.pendingBooking = draft; sessionStorage.setItem(bookingDraftKey, JSON.stringify(draft)); db.route = 'book'; save(); render(); };
window.startWalkIn = () => { db.pendingBooking = { salonId: db.activeSalonId, serviceId: salonServices()[0]?.id, staffId: 'any', date: today, time: '', forWhom: 'family', walkIn: true, step: 1 }; db.route = 'book'; save(); render(); };
function availableSlots(pending) { db.slotHolds = db.slotHolds.filter((h) => h.expiresAt > Date.now()); const staffIds = db.staff.filter((p) => p.salonId === pending.salonId && p.available && (pending.staffId === 'any' || p.id === pending.staffId)).map((p) => p.id); return times.filter((time) => isBookableDateTime(pending.salonId, pending.date, time) && !db.holidays.some((h) => h.salonId === pending.salonId && h.date === pending.date) && !db.blockedTimes.some((b) => b.salonId === pending.salonId && b.date === pending.date && b.time === time) && !db.slotHolds.some((h) => h.salonId === pending.salonId && h.date === pending.date && h.time === time && h.customerId !== bookingVisitorId() && (h.staffId === 'any' || pending.staffId === 'any' || h.staffId === pending.staffId)) && staffIds.some((staffId) => !db.bookings.some((b) => b.staffId === staffId && b.date === pending.date && b.time === time && ['Pending', 'Confirmed'].includes(b.status)))); }
function persistBookingDraft() { sessionStorage.setItem(bookingDraftKey, JSON.stringify(db.pendingBooking)); save(); }
window.selectBookingSalon = (salonId) => { const services = salonServices(salonId); Object.assign(db.pendingBooking, { salonId, serviceId: services[0]?.id || '', staffId: 'any', date: today, time: '', heldUntil: 0 }); db.activeSalonId = salonId; persistBookingDraft(); render(); };
window.selectBookingService = (serviceId) => { Object.assign(db.pendingBooking, { serviceId, offerId: undefined, offerSelectionInitialized: false }); persistBookingDraft(); render(); };
window.selectBookingOffer = (offerId) => { Object.assign(db.pendingBooking, { offerId: offerId || '', offerSelectionInitialized: true }); persistBookingDraft(); render(); };
window.selectBookingStaff = (staffId) => { Object.assign(db.pendingBooking, { staffId, time: '', heldUntil: 0 }); persistBookingDraft(); render(); };
window.selectBookingDate = (date) => { Object.assign(db.pendingBooking, { date, time: '', heldUntil: 0 }); persistBookingDraft(); render(); };
window.goToBookingStep = (step) => { const pending = db.pendingBooking; if (!pending) return; if (step > 1 && !pending.serviceId) return; if (step > 2 && !pending.staffId) return; if (step > 3 && (!pending.time || pending.heldUntil <= Date.now())) return; pending.step = Math.min(4, Math.max(1, step)); persistBookingDraft(); render(); };
window.returnToSlotSelection = () => { const pending = db.pendingBooking; if (!pending) return; if (!pending.heldUntil || pending.heldUntil <= Date.now()) { db.slotHolds = db.slotHolds.filter((hold) => hold.customerId !== bookingVisitorId()); Object.assign(pending, { time: '', heldUntil: 0 }); } pending.step = 3; persistBookingDraft(); render(); };
window.updateBookingDraft = () => { Object.assign(db.pendingBooking, { salonId: val('book-salon') || db.pendingBooking.salonId, serviceId: val('book-service') || db.pendingBooking.serviceId, staffId: val('book-staff') || db.pendingBooking.staffId, date: val('book-date') || db.pendingBooking.date }); db.activeSalonId = db.pendingBooking.salonId; persistBookingDraft(); render(); };
window.holdSlot = (time) => { if (!isBookableDateTime(db.pendingBooking.salonId, db.pendingBooking.date, time)) return alert(`Choose a time at least ${bookingRules(db.pendingBooking.salonId).leadHours} hours from now.`); db.pendingBooking.time = time; db.pendingBooking.heldUntil = Date.now() + 300000; db.slotHolds = db.slotHolds.filter((h) => h.expiresAt > Date.now() && h.customerId !== bookingVisitorId()); db.slotHolds.push({ salonId: db.pendingBooking.salonId, staffId: db.pendingBooking.staffId, date: db.pendingBooking.date, time, customerId: bookingVisitorId(), expiresAt: db.pendingBooking.heldUntil }); persistBookingDraft(); render(); };
const bookingDateLabel = (date, options) => new Intl.DateTimeFormat('en-IN', { timeZone: 'UTC', ...options }).format(new Date(`${date}T00:00:00Z`));
function bookingProgress(step) { const labels = ['Service', 'Specialist', 'Date & time', 'Confirm']; return `<ol class="booking-progress" aria-label="Booking progress">${labels.map((label, index) => `<li class="${step === index + 1 ? 'active' : ''} ${step > index + 1 ? 'complete' : ''}"><span>${step > index + 1 ? '✓' : index + 1}</span><small>${label}</small></li>`).join('')}</ol>`; }
function bookingActions(step, canContinue = true) { return `<div class="booking-step-actions">${step > 1 ? `<button class="ghost" onclick="goToBookingStep(${step - 1})">← Back</button>` : '<span></span>'}<button onclick="goToBookingStep(${step + 1})" ${canContinue ? '' : 'disabled'}>Continue →</button></div>`; }
function bookingOfferSelector(pending, service) {
  const offers = serviceOffers(service, true);
  const eligible = offers.filter((offer) => offerSaving(offer, service) > 0);
  if (!pending.offerSelectionInitialized) {
    pending.offerId = eligible[0]?.id || '';
    pending.offerSelectionInitialized = true;
    persistBookingDraft();
  }
  const applied = eligible.find((offer) => offer.id === pending.offerId) || null;
  const saving = offerSaving(applied, service);
  const unavailableReason = (offer) => !offerAppliesToService(offer, service) ? 'Only valid on selected services' : service.price < offerMinimum(offer) ? `Minimum booking ${fmt(offerMinimum(offer))}` : 'Not eligible for this booking';
  return `<section class="offer-selector" aria-labelledby="offer-selector-title"><div class="offer-selector-head"><span><small>OFFERS & COUPONS</small><b id="offer-selector-title">${applied ? `${applied.title} applied` : 'Apply coupon / Select offer'}</b>${saving ? `<em>You're saving ${fmt(saving)}</em>` : '<em>Browse eligible savings</em>'}</span>${applied ? `<button class="text-button" onclick="selectBookingOffer('')" aria-label="Remove applied offer">Remove</button>` : ''}</div><details><summary aria-label="Browse available offers">${offers.length ? `View ${offers.length} available offer${offers.length === 1 ? '' : 's'}` : 'No offers available'} <span>⌄</span></summary><div class="offer-options" role="radiogroup" aria-label="Available booking offers">${offers.map((offer) => { const save = offerSaving(offer, service); const disabled = !save; return `<button type="button" role="radio" aria-checked="${offer.id === pending.offerId}" class="offer-option ${offer.id === pending.offerId ? 'selected' : ''}" onclick="selectBookingOffer('${offer.id}')" ${disabled ? `disabled title="${unavailableReason(offer)}"` : ''}><span class="offer-radio"></span><span><b>${offer.title}</b><small>${disabled ? unavailableReason(offer) : `${offerDiscount(offer)} · Save ${fmt(save)}`}</small></span>${offer === eligible[0] ? '<mark>BEST VALUE</mark>' : ''}</button>`; }).join('') || '<p class="empty">There are no active offers for this service right now.</p>'}<p class="offer-stack-note">ⓘ One offer per booking. Selecting another offer replaces the current one.</p></div></details></section>`;
}
function booking() {
  const pending = db.pendingBooking || { salonId: db.activeSalonId, serviceId: salonServices()[0]?.id, staffId: 'any', date: today, time: '', forWhom: 'self', step: 1 };
  db.pendingBooking = pending;
  pending.step = Math.min(4, Math.max(1, Number(pending.step) || 1));
  const service = db.services.find((item) => item.id === pending.serviceId);
  const salonItem = db.salons.find((item) => item.id === pending.salonId);
  const staff = db.staff.filter((person) => person.salonId === pending.salonId && person.available);
  const specialist = staff.find((person) => person.id === pending.staffId);
  const rules = bookingRules(pending.salonId);
  const heading = `<div class="booking-heading"><button class="booking-close ghost" onclick="openSalon('${pending.salonId}')" aria-label="Close booking">←</button><div><p class="eyebrow">Pay at salon</p><h1>${pending.walkIn ? 'Add walk-in booking' : 'Book appointment'}</h1><p>${salonItem?.name || ''}</p></div></div>${bookingProgress(pending.step)}`;
  let content = '';
  if (pending.step === 1) {
    const services = salonServices(pending.salonId);
    content = `<div class="booking-step-head"><p>Step 1 of 4</p><h2>Choose a service</h2><span>Select what you would like to book at <strong>${salonItem?.name || 'this salon'}</strong>.</span></div><div class="booking-choice-list">${services.map((item) => `<button class="booking-choice ${item.id === pending.serviceId ? 'selected' : ''}" onclick="selectBookingService('${item.id}')"><span><b>${item.name}</b><small>${item.category} · ${item.duration} min</small></span>${servicePriceMarkup(item, bestServiceOffer(item), true)}<i>✓</i></button>`).join('') || '<p class="empty">No services are currently available.</p>'}</div>${bookingActions(1, Boolean(pending.serviceId))}`;
  } else if (pending.step === 2) {
    const anySelected = pending.staffId === 'any';
    content = `<div class="booking-step-head"><p>Step 2 of 4</p><h2>Choose a specialist</h2><span>Pick a team member or choose the first available.</span></div><div class="specialist-grid"><button class="specialist-card ${anySelected ? 'selected' : ''}" onclick="selectBookingStaff('any')"><span class="specialist-avatar">Any</span><b>Any specialist</b><small>First available</small><i>✓</i></button>${staff.map((person) => `<button class="specialist-card ${person.id === pending.staffId ? 'selected' : ''}" onclick="selectBookingStaff('${person.id}')"><span class="specialist-avatar">${person.name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2)}</span><b>${person.name}</b><small>${person.specialization}</small><i>✓</i></button>`).join('')}</div>${bookingActions(2, Boolean(pending.staffId))}`;
  } else if (pending.step === 3) {
    const dates = Array.from({ length: rules.windowDays + 1 }, (_, index) => addDays(today, index)).slice(0, 14);
    const slots = availableSlots(pending);
    const held = pending.heldUntil > Date.now() && bookingSelectionIsValid(pending);
    content = `<div class="booking-step-head"><p>Step 3 of 4</p><h2>Choose date & time</h2><span>Times shown are in the salon's local time.</span></div><label class="booking-date-picker">Choose another date<input id="book-date" type="date" min="${today}" max="${addDays(today, rules.windowDays)}" value="${pending.date}" onchange="selectBookingDate(this.value)"></label><div class="booking-month">${bookingDateLabel(pending.date, { month: 'long', year: 'numeric' })}</div><div class="booking-date-strip">${dates.map((date) => `<button class="booking-date ${date === pending.date ? 'selected' : ''}" onclick="selectBookingDate('${date}')"><small>${bookingDateLabel(date, { weekday: 'short' })}</small><b>${bookingDateLabel(date, { day: 'numeric' })}</b></button>`).join('')}</div><h3 class="slot-heading">Available slots</h3><div class="slot-grid">${slots.map((time) => `<button class="slot ${pending.time === time ? 'selected' : ''}" onclick="holdSlot('${time}')">${new Date(`2000-01-01T${time}:00`).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</button>`).join('') || '<p class="empty">No slots available. Choose another date or specialist.</p>'}</div>${held ? '<div class="hold-note">✓ Slot held for 5 minutes while you finish.</div>' : ''}${bookingActions(3, held)}`;
  } else {
    const selectionValid = bookingSelectionIsValid(pending);
    const offerSelector = bookingOfferSelector(pending, service);
    const appliedOffer = serviceOffers(service).find((offer) => offer.id === pending.offerId) || null;
    const price = servicePrice(service, appliedOffer);
    const bookingMobile = pending.guestMobile || currentCustomer()?.mobile || '';
    content = `<div class="booking-step-head"><p>Step 4 of 4</p><h2>Confirm your appointment</h2><span>Check the details before sending your request.</span></div><div class="booking-review"><div><small>Service</small><b>${service?.name || ''}</b><span>${service?.duration || 0} min · ${fmt(service?.price || 0)}</span></div><div><small>Specialist</small><b>${specialist?.name || 'Any available specialist'}</b><span>${specialist?.specialization || 'First available'}</span></div><div><small>Date & time</small><b>${bookingDateLabel(pending.date, { weekday: 'long', day: 'numeric', month: 'long' })}</b><span>${new Date(`2000-01-01T${pending.time}:00`).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</span></div></div>${offerSelector}<label>${pending.walkIn ? 'Customer name' : 'Booking for'}<select id="book-for"><option value="self" ${pending.forWhom !== 'family' ? 'selected' : ''}>Myself</option><option value="family" ${pending.forWhom === 'family' || pending.walkIn ? 'selected' : ''}>Family member / walk-in guest</option></select></label><div class="form-grid"><label>Guest name <small>(required for another person)</small><input id="book-name" placeholder="Full name" value="${pending.guestName || ''}"></label><label>Mobile number <small>(required)</small><input id="book-mobile" type="tel" inputmode="tel" autocomplete="tel" required placeholder="98765 43210" value="${bookingMobile}"></label></div><label>Note <small>(optional)</small><textarea id="book-note" rows="2" placeholder="Anything the salon should know">${pending.note || ''}</textarea></label><div class="price-breakdown" aria-live="polite"><div><span>Service subtotal</span><span>${fmt(price.original)}</span></div>${price.saving ? `<div class="savings-row"><span>Offer savings</span><span>−${fmt(price.saving)}</span></div>` : ''}<div class="total-row"><strong>Total at salon</strong><strong>${fmt(price.final)}</strong></div></div><div class="booking-summary"><span>${rules.confirmationMode === 'automatic' ? 'Instant confirmation' : 'Salon confirmation required'}</span><strong>${fmt(price.final)}</strong></div><div class="booking-step-actions"><button class="ghost" onclick="returnToSlotSelection()">← Back</button><button onclick="confirmBooking()" ${selectionValid ? '' : 'disabled'}>${pending.walkIn ? 'Add walk-in' : 'Confirm booking'}</button></div><p id="book-error" class="error" role="alert"></p>`;
  }
  return `<section class="booking-flow">${heading}<div class="booking-step-card">${content}</div></section>`;
}
window.confirmBooking = async () => { const pending = db.pendingBooking; if (!bookingSelectionIsValid(pending)) return text('book-error', 'This appointment time is no longer available. Select another time.'); Object.assign(pending, { forWhom: val('book-for'), guestName: val('book-name').trim(), guestMobile: val('book-mobile').trim(), note: val('book-note') }); if (!pending.guestMobile) return text('book-error', 'Enter a mobile number to book this appointment.'); if ((pending.forWhom === 'family' || pending.walkIn) && !pending.guestName) return text('book-error', 'Enter the guest name.'); sessionStorage.setItem(bookingDraftKey, JSON.stringify(pending)); if (!session) { loginRole = 'customer'; authMode = 'signin'; authModal = { trigger: 'booking', returnRoute: 'book' }; render(); return; } if (session.role === 'owner') { authModal = { trigger: 'role_mismatch' }; render(); return; } await submitBookingRequest(pending); };
async function persistBookingRequest(booking, customer, notification) {
  clearTimeout(saveTimer);
  for (let attempt = 0; attempt < 2; attempt += 1) {
    const response = await fetch('/api/state', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ app: persistedAppState(), revision: stateRevision }) });
    const payload = await response.json().catch(() => ({}));
    if (response.ok) { stateRevision = payload.revision; return true; }
    if (response.status !== 409 || attempt === 1) throw new Error(payload.error || 'Unable to save your booking request.');
    const latestResponse = await fetch('/api/state', { cache: 'no-store' });
    if (!latestResponse.ok) throw new Error('Unable to refresh booking availability.');
    const latest = await latestResponse.json();
    db = { ...db, ...(latest.app || {}) };
    db.customers = [...(db.customers || []).filter((item) => item.id !== customer.id), customer];
    db.bookings = [...(db.bookings || []).filter((item) => item.id !== booking.id), booking];
    db.ownerNotifications = [notification, ...(db.ownerNotifications || []).filter((item) => item.bookingId !== booking.id)];
    stateRevision = latest.revision || 0;
  }
  return false;
}
async function submitBookingRequest(pending) {
  const service = db.services.find((item) => item.id === pending.serviceId);
  const possibleStaff = db.staff.filter((person) => person.salonId === pending.salonId && person.available && (pending.staffId === 'any' || person.id === pending.staffId));
  const staffId = possibleStaff.find((person) => !db.bookings.some((booking) => booking.staffId === person.id && booking.date === pending.date && booking.time === pending.time && ['Pending', 'Confirmed'].includes(booking.status)))?.id;
  if (!staffId) return text('book-error', 'That slot is no longer available. Please select another time.');
  let customer = ensureSessionCustomer();
  if (!pending.guestMobile?.trim()) return text('book-error', 'Enter a mobile number to book this appointment.');
  if (pending.forWhom === 'family' || pending.walkIn) {
    customer = { ...customer, id: `cus-${Date.now()}`, name: pending.guestName, mobile: pending.guestMobile, visits: 0, totalSpend: 0, favoriteSalons: [] };
    db.customers.push(customer);
  } else {
    customer.mobile = pending.guestMobile.trim();
  }
  const booking = { id: `book-${Date.now()}`, salonId: pending.salonId, customerId: customer.id, bookedByCustomerId: currentCustomer().id, serviceId: pending.serviceId, staffId, date: pending.date, time: pending.time, status: pending.walkIn || bookingRules(pending.salonId).confirmationMode === 'automatic' ? 'Confirmed' : 'Pending', amount: servicePrice(service, serviceOffers(service).find((offer) => offer.id === pending.offerId)).final, originalAmount: service.price, discountAmount: offerSaving(serviceOffers(service).find((offer) => offer.id === pending.offerId), service), duration: service.duration, note: pending.note || '', source: pending.walkIn ? 'walk_in' : 'online', paymentStatus: 'Pay at salon', campaignId: db.clickedCampaignId || '', offerId: pending.offerId || db.clickedOfferId || '' };
  if (booking.status === 'Confirmed' && !pending.walkIn) db.notifications.unshift({ customerId: customer.id, bookingId: booking.id, message: 'Your booking was confirmed automatically.', read: false });
  const notification = { salonId: booking.salonId, bookingId: booking.id, message: `New ${booking.source === 'walk_in' ? 'walk-in' : 'online'} booking from ${customer.name}`, read: false };
  db.bookings.push(booking);
  db.ownerNotifications.unshift(notification);
  try {
    await persistBookingRequest(booking, customer, notification);
  } catch (error) {
    db.bookings = db.bookings.filter((item) => item.id !== booking.id);
    db.ownerNotifications = db.ownerNotifications.filter((item) => item.bookingId !== booking.id);
    return text('book-error', error.message);
  }
  db.slotHolds = db.slotHolds.filter((hold) => hold.customerId !== currentCustomer().id);
  db.pendingBooking = null;
  sessionStorage.removeItem(bookingDraftKey);
  db.activeBookingId = booking.id;
  db.route = pending.walkIn ? 'owner-bookings' : 'booking-details';
  render();
}
const customerOwnsBooking = (bookingItem) => { const customer = currentCustomer(); return Boolean(customer && (bookingItem.customerId === customer.id || bookingItem.bookedByCustomerId === customer.id)); };
window.openBookingDetails = (id) => { const bookingItem = db.bookings.find((item) => item.id === id); if (!bookingItem || !customerOwnsBooking(bookingItem)) return; db.activeBookingId = id; db.route = 'booking-details'; render(); };
function bookingDetails() { const bookingItem = db.bookings.find((item) => item.id === db.activeBookingId); if (!bookingItem || !customerOwnsBooking(bookingItem)) return `<h1>Booking details</h1>${card('<p>Booking not found.</p><button onclick="navigate(\'my-bookings\')">Back to my bookings</button>')}`; return `<div class="page-heading"><div><p class="eyebrow">Booking saved</p><h1>Booking details</h1><p>Your appointment request has been saved successfully.</p></div><button class="ghost" onclick="navigate('my-bookings')">All bookings</button></div>${customerBookingCard(bookingItem)}`; }
function myBookings() { const mine = db.bookings.filter(customerOwnsBooking); return `<h1>My bookings</h1><h2>Upcoming appointments</h2>${mine.filter((b) => ['Pending', 'Confirmed'].includes(b.status)).map(customerBookingCard).join('') || card('No upcoming appointments.')}<h2>Previous appointments</h2>${mine.filter((b) => !['Pending', 'Confirmed'].includes(b.status)).map(customerBookingCard).join('') || card('No previous appointments yet.')}`; }
  function customerBookingCard(b) { const s = db.salons.find((item) => item.id === b.salonId); const service = db.services.find((item) => item.id === b.serviceId); const customer = db.customers.find((item) => item.id === b.customerId); const salonName = s?.name || 'Salon unavailable'; const serviceName = service?.name || 'Service unavailable'; const message = `Hi ${customer?.name || 'there'}, your booking at ${salonName} is ${b.status.toLowerCase()} for ${serviceName} on ${b.date} at ${b.time}.`; const upcoming = ['Pending', 'Confirmed'].includes(b.status); const explanation = b.status === 'Pending' ? '<p class="booking-state-note">Waiting for the salon owner to confirm this request.</p>' : ''; return card(`<div class="booking-card-head"><div><h3>${serviceName}</h3><p>${salonName} · ${b.date} at ${b.time}</p></div>${statusChip(b.status)}</div>${explanation}<p>${service?.duration ? `${service.duration} min · ` : ''}${fmt(b.amount)} · Pay at salon</p>${b.note ? `<p>Note: ${b.note}</p>` : ''}<div class="actions"><button class="ghost" onclick="openBookingDetails('${b.id}')">View details</button>${upcoming ? `<button class="danger" onclick="cancelBooking('${b.id}')">Cancel</button><button class="ghost" onclick="rescheduleBooking('${b.id}')">Reschedule</button>${s?.whatsapp ? `<a target="_blank" href="${wa(s.whatsapp, message)}">WhatsApp</a>` : ''}` : b.status === 'Completed' && service ? `<button onclick="rebook('${b.id}')">Rebook</button>` : ''}</div>`, 'booking-card'); }
window.rebook = (id) => { const bookingItem = db.bookings.find((item) => item.id === id); db.activeSalonId = bookingItem.salonId; startBooking(bookingItem.serviceId); };
function beforeCutoff(b) { return new Date(`${b.date}T${b.time}:00+05:30`).getTime() - Date.now() >= cancellationCutoff(b.salonId) * 3600000; }
window.cancelBooking = (id) => { const booking = db.bookings.find((b) => b.id === id); if (!beforeCutoff(booking)) return alert(`Cancellation closes ${cancellationCutoff(booking.salonId)} hours before the appointment.`); booking.status = 'Cancelled'; save(); render(); };
window.rescheduleBooking = (id) => { const b = db.bookings.find((item) => item.id === id); if (!beforeCutoff(b)) return alert(`Rescheduling closes ${cancellationCutoff(b.salonId)} hours before the appointment.`); b.status = 'Cancelled'; db.activeSalonId = b.salonId; db.pendingBooking = { ...b, time: '', heldUntil: 0, walkIn: false }; navigate('book'); };
function myOffers() { const offers = recommendedOffers(); return `<h1>My offers</h1>${offers.map(offerCard).join('')}`; }
function offerCard(offer, salonId = offer.salonId) { const s = db.salons.find((item) => item.id === salonId); return card(`${offer.segment ? `<p class="pill">${offer.segment}</p>` : ''}<h3>${offer.title}</h3>${offer.description ? `<p>${offer.description}</p>` : ''}<p>${s?.name || 'Zaya'}${offer.end ? ` • Valid until ${offer.end}` : ''}</p><button onclick="redeemOffer('${offer.id}', '${salonId}')">Book Now</button>`); }
window.redeemOffer = (id, salonId = '') => { const offer = [...db.offers, ...(db.platformOffers || []).map((item) => ({ ...item, start: item.startDate, end: item.endDate }))].find((item) => item.id === id); if (!offerIsEligible(offer)) return alert('This offer is no longer available.'); offer.clicks = (offer.clicks || 0) + 1; db.clickedOfferId = id; db.activeSalonId = salonId || offer.salonId; db.route = 'salon-profile'; save(); render(); };
function profile() { const c = currentCustomer(); const displayName = activeDisplayName(); const favorites = db.salons.filter((s) => c.favoriteSalons.includes(s.id)); return `<section class="profile-hero"><div class="profile-avatar">${initials(displayName)}</div><div class="profile-identity"><p class="eyebrow">My account</p><h1>${displayName}</h1><p class="profile-meta"><span>⌖ ${c.location || 'Palakkad'}</span><i>•</i><span>◎ ${c.language || 'English'}</span></p><button onclick="navigate('register')">Edit Profile</button></div></section><div class="profile-metrics"><div><span class="metric-icon">▣</span><div><strong>${c.visits}</strong><span>Visits</span></div></div><div><span class="metric-icon">₹</span><div><strong>${fmt(c.totalSpend)}</strong><span>Total Spend</span></div></div><div><span class="metric-icon">♡</span><div><strong>${favorites.length}</strong><span>Saved Salons</span></div></div></div><div class="section-title favorite-heading"><h2>Favorite Salons</h2></div>${favorites.length ? salonList('', favorites) : `<section class="favorites-empty"><div class="empty-heart">♡</div><h3>No favorite salons yet</h3><p>Save your favorite spots to easily book them again later.</p><button onclick="navigate('explore')">Explore Nearby Salons</button></section>`}`; }
function ownerDashboard() { const salonId = db.activeSalonId; const bookings = db.bookings.filter((b) => b.salonId === salonId); const pending = bookings.filter((b) => b.status === 'Pending' && b.date >= today); const alerts = db.ownerNotifications.filter((n) => n.salonId === salonId && !n.read); return `<div class="page-heading"><div><p class="eyebrow">Today · ${today}</p><h1>${salon().name}</h1><p>${alerts.length} new booking notification${alerts.length === 1 ? '' : 's'}</p></div><button onclick="startWalkIn()">+ Walk-in</button></div><div class="grid stats">${[['Today', bookings.filter((b) => b.date === today).length], ['Awaiting confirmation', pending.length], ['Upcoming', bookings.filter((b) => b.date >= today && ['Pending','Confirmed'].includes(b.status)).length], ['Completed', bookings.filter((b) => b.status === 'Completed').length], ['Cancellations', bookings.filter((b) => b.status === 'Cancelled').length]].map(([a, b]) => card(`<span>${a}</span><b>${b}</b>`)).join('')}</div><h2>Booking requests</h2>${ownerBookingList(pending) || card('No booking requests waiting for confirmation.')}<h2>Today's appointments</h2>${ownerBookingList(bookings.filter((b) => b.date === today && b.status !== 'Pending')) || card('No confirmed appointments today.')}`; }
  function ownerBookingList(bookings) { return bookings.sort((a,b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).map(ownerBookingCard).join(''); }
  function ownerBookingCard(b) { const c = db.customers.find((item) => item.id === b.customerId); const service = db.services.find((item) => item.id === b.serviceId); const reminder = `Hi ${c.name}, reminder: your ${service.name} appointment at ${salon().name} is on ${b.date} at ${b.time}.`; const workflowActions = b.status === 'Pending' ? `<button onclick="updateBooking('${b.id}','Confirmed')">Confirm booking</button><button class="danger" onclick="updateBooking('${b.id}','Cancelled')">Decline</button>` : b.status === 'Confirmed' ? `<button onclick="updateBooking('${b.id}','Completed')">Mark completed</button><button class="ghost" onclick="updateBooking('${b.id}','No-show')">No-show</button>` : ''; const staffOptions = db.staff.filter((person) => person.salonId === b.salonId && person.available).map((person) => `<option value="${person.id}" ${person.id === b.staffId ? 'selected' : ''}>${person.name}</option>`).join(''); return card(`<div class="booking-card-head"><div><b>${b.time} · ${c.name}</b><p>${service.name} · ${service.duration} min · ${fmt(b.amount)}</p></div>${statusChip(b.status)}</div>${b.note ? `<p>Customer note: ${b.note}</p>` : ''}<div class="actions">${workflowActions}<a target="_blank" href="${wa(c.mobile, reminder)}">WhatsApp</a></div><details class="booking-editor"><summary>Edit booking</summary><div class="form-grid"><label>Date<input id="owner-date-${b.id}" type="date" min="${today}" value="${b.date}"></label><label>Time<select id="owner-time-${b.id}">${times.map((time) => `<option ${time === b.time ? 'selected' : ''}>${time}</option>`)}</select></label><label>Staff<select id="owner-staff-${b.id}">${staffOptions}</select></label><label>Internal / customer note<input id="owner-note-${b.id}" value="${b.note || ''}"></label></div><button onclick="saveBookingEdit('${b.id}')">Save changes</button></details>`, `booking-card ${b.status === 'Pending' ? 'booking-request' : ''}`); }
function ownerBookings() { const list = db.bookings.filter((b) => b.salonId === db.activeSalonId); return `<div class="page-heading"><div><h1>Appointment calendar</h1><p>Daily and upcoming bookings in one simple list.</p></div><button onclick="startWalkIn()">+ Add walk-in</button></div><h2>Today</h2>${ownerBookingList(list.filter((b) => b.date === today)) || card('No bookings today.')}<h2>Upcoming</h2>${ownerBookingList(list.filter((b) => b.date > today && !['Cancelled','Completed','No-show'].includes(b.status))) || card('No upcoming bookings.')}`; }
  window.updateBooking = (id, status) => { const b = db.bookings.find((item) => item.id === id); b.status = status; if (status === 'Completed') { const c = db.customers.find((item) => item.id === b.customerId); c.visits += 1; c.totalSpend += b.amount; if (b.offerId && !db.redemptions.some((r) => r.bookingId === id)) db.redemptions.push({ id: `red-${Date.now()}`, offerId: b.offerId, bookingId: id, customerId: b.customerId, amount: b.amount }); } save(); render(); };
  window.saveBookingEdit = (id) => { const booking = db.bookings.find((item) => item.id === id); const date = val(`owner-date-${id}`); const time = val(`owner-time-${id}`); const staffId = val(`owner-staff-${id}`); const conflict = db.bookings.some((item) => item.id !== id && item.staffId === staffId && item.date === date && item.time === time && ['Pending', 'Confirmed'].includes(item.status)); if (conflict) return alert('That staff member already has a booking in this slot.'); Object.assign(booking, { date, time, staffId, note: val(`owner-note-${id}`).trim() }); save(); render(); };
function crm() { const customers = ownerCustomers(); return `<h1>Customer CRM</h1><input id="crm-search" placeholder="Search/filter customers" oninput="render()" value="${document.getElementById('crm-search')?.value || ''}"><div class="grid three">${customers.filter((c) => (`${c.name} ${c.mobile} ${c.location}`).toLowerCase().includes((document.getElementById('crm-search')?.value || '').toLowerCase())).map((c) => card(`<h3>${c.name}</h3><p>${c.mobile} • ${c.location}</p><p>Last visit: ${lastVisit(c.id) || 'Never'} • ${c.visits} visits • ${fmt(c.totalSpend)}</p><p>Favorite services: ${favoriteServices(c.id).join(', ') || 'New customer'}</p><button onclick="customerNote('${c.id}')">Add note</button>`)).join('')}</div>`; }
window.customerNote = (id) => { const c = db.customers.find((item) => item.id === id); c.note = prompt('Customer note', c.note || '') || c.note; save(); render(); };
function ownerCustomers() { const ids = new Set(db.bookings.filter((b) => b.salonId === db.activeSalonId).map((b) => b.customerId)); return db.customers.filter((c) => ids.has(c.id)); }
function lastVisit(customerId) { return db.bookings.filter((b) => b.customerId === customerId && b.status === 'Completed').sort((a, b) => b.date.localeCompare(a.date))[0]?.date; }
function favoriteServices(customerId) { return [...new Set(db.bookings.filter((b) => b.customerId === customerId).map((b) => db.services.find((s) => s.id === b.serviceId)?.name).filter(Boolean))].slice(0, 3); }
function segmentCustomers(id) { const salonCustomerIds = new Set(db.bookings.filter((b) => b.salonId === db.activeSalonId).map((b) => b.customerId)); return db.customers.filter((c) => { const visits = db.bookings.filter((b) => b.customerId === c.id && b.salonId === db.activeSalonId && b.status === 'Completed'); const last = lastVisit(c.id); const days = last ? Math.floor((new Date(today) - new Date(last)) / 86400000) : 999; const svc = favoriteServices(c.id); if (id === 'new') return !salonCustomerIds.has(c.id); if (id === 'regular') return visits.length >= 2; if (id === 'inactive-30') return visits.length > 0 && days >= 30; if (id === 'inactive-60') return visits.length > 0 && days >= 60; if (id === 'inactive-facial-60') return svc.includes('Facial') && days >= 60; if (id === 'birthday-month') return c.dob?.slice(5, 7) === '08'; if (id === 'high-value') return c.totalSpend >= 5000; if (id === 'female-nearby') return c.gender === 'Female' && ['Palakkad', 'Kinassery', 'Koduvayur'].includes(c.location); return false; }); }
function offers() { return `<h1>Targeted offers</h1>${card(`<h2>Create offer</h2><label>Offer title<input id="offer-title" placeholder="Offer title"></label><label>Description<input id="offer-description" placeholder="Describe the offer"></label><label>Discount type<select id="offer-type"><option>Percentage</option><option>Fixed amount</option><option>Buy one get one</option><option>Service bundle</option><option>First visit offer</option><option>Come-back offer</option><option>Birthday offer</option></select></label><label>Discount<input id="offer-discount" type="number" min="1"></label><label>Applicable service<input id="offer-service" placeholder="Service name"></label><label>Target segment<input id="offer-segment" value="${db.selectedSegmentId || ''}" placeholder="Audience segment"></label><label>End date<input id="offer-end" type="date" min="${today}"></label><label>Terms<input id="offer-terms" placeholder="Offer terms"></label><button onclick="previewOffer()">Preview</button> <button onclick="createOffer()">Submit for review</button><div id="offer-preview"></div>`)}<div class="grid three">${db.offers.filter((o) => o.salonId === db.activeSalonId).map(offerCard).join('')}</div>`; }
window.previewOffer = () => text('offer-preview', `${val('offer-title')} • ${val('offer-discount')}% • Target: ${val('offer-segment')} • Valid until ${val('offer-end')}`);
window.createOffer = () => { db.offers.unshift({ id: `offer-${Date.now()}`, salonId: db.activeSalonId, title: val('offer-title'), description: val('offer-description'), type: val('offer-type'), discount: Number(val('offer-discount')), service: val('offer-service'), segment: val('offer-segment'), start: today, end: val('offer-end'), minPurchase: 0, maxRedemptions: 100, terms: val('offer-terms'), approvalStatus: 'pending', status: 'pending', active: false, views: 0, clicks: 0, redemptions: 0 }); save(); render(); };
function marketing() { const ownerOffers = [...availablePlatformOffers(), ...db.offers.filter((o) => o.salonId === db.activeSalonId && offerIsEligible(o))]; const audiences = [['inactive-facial-60', 'Inactive facial', '60+ days'], ['regular', 'Regular customers', '2+ visits'], ['birthday-month', 'Birthdays', 'This month'], ['high-value', 'High value', '₹5,000+ spent']]; return `<div class="page-heading"><div><p class="eyebrow">Marketing</p><h1>Send a targeted campaign</h1><p>Choose an audience, offer and channel. Everything is managed in one place.</p></div></div><div class="grid stats audience-stats">${audiences.map(([id, label, rule]) => card(`<span>${label}</span><b>${segmentCustomers(id).length}</b><small>${rule}</small>`)).join('')}</div>${card(`<h2>Audience → Offer → Channel</h2><div class="form-grid"><label>Audience<select id="camp-segment">${audiences.map(([id, label]) => `<option value="${id}">${label} (${segmentCustomers(id).length})</option>`).join('')}</select></label><label>Offer<select id="camp-offer">${ownerOffers.length ? ownerOffers.map((o) => `<option value="${o.id}">${o.title}</option>`).join('') : '<option value="">No active offers available</option>'}</select></label><label>Channel<select id="camp-channel"><option>In-app notification</option><option>WhatsApp click-to-chat</option><option disabled>SMS (coming later)</option><option disabled>Email (coming later)</option></select></label></div><button onclick="sendCampaign()" ${ownerOffers.length ? '' : 'disabled'}>Send campaign</button>`)}<h2>Campaign history</h2><div class="grid three">${db.campaigns.filter((c) => c.salonId === db.activeSalonId).map(campaignCard).join('') || card('No campaigns sent yet.')}</div>`; }
window.sendCampaign = () => { const audience = segmentCustomers(val('camp-segment')); const campaign = { id: `camp-${Date.now()}`, salonId: db.activeSalonId, name: `${val('camp-segment')} campaign`, segmentId: val('camp-segment'), offerId: val('camp-offer'), channel: val('camp-channel'), status: 'Sent', targeted: audience.length, sent: audience.length, views: 0, clicks: 0, bookings: 0, redemptions: 0, revenue: 0 }; db.campaigns.unshift(campaign); db.notifications.push(...audience.map((c) => ({ customerId: c.id, campaignId: campaign.id, offerId: campaign.offerId, read: false }))); save(); render(); };
function campaignCard(c) { const offer = [...(db.platformOffers || []), ...db.offers].find((o) => o.id === c.offerId); return card(`<p class="pill">${c.status}</p><h3>${c.name}</h3><p>${offer?.title || 'Offer'} • ${c.channel}</p><p>Targeted ${c.targeted} • Sent ${c.sent} • Views ${c.views} • Clicks ${c.clicks}</p><p>Bookings ${c.bookings} • Redemptions ${c.redemptions} • Revenue ${fmt(c.revenue)}</p>`); }
function settings() {
  const s = salon();
  const staff = db.staff.filter((item) => item.salonId === s.id);
  const services = db.services.filter((item) => item.salonId === s.id);
  return `<div class="page-heading"><div><p class="eyebrow">Salon setup</p><h1>Manage your salon</h1><p>Update the details customers see when they book.</p></div><button onclick="openSalon('${s.id}')">View public page</button></div>
  ${card(`<h2>Salon details</h2><div class="form-grid"><label>Salon name<input id="salon-name" value="${s.name}"></label><label>Phone<input id="salon-phone" value="${s.phone}"></label><label>Address<input id="salon-address" value="${s.address}"></label><label>Town / location<input id="salon-location" value="${s.location}"></label><label>Opening hours<input id="salon-hours" value="${s.openingHours}"></label><label>WhatsApp number<input id="salon-whatsapp" value="${s.whatsapp}"></label></div><label>Description<textarea id="salon-description" rows="3">${s.description}</textarea></label><h3>Map location</h3><p class="help">Click or drag the pin to the salon entrance. This location is used for customer directions.</p><div id="salon-location-map" class="salon-location-map" data-latitude="${s.latitude ?? ''}" data-longitude="${s.longitude ?? ''}"></div><input id="salon-latitude" type="hidden" value="${s.latitude ?? ''}"><input id="salon-longitude" type="hidden" value="${s.longitude ?? ''}"><label>Salon photo<input id="salon-photo" type="file" accept="image/png,image/jpeg,image/webp" onchange="previewSalonPhoto(this)"></label><div id="photo-preview" class="photo-preview"><img src="${salonPhoto(s)}" alt="Salon photo preview"></div><p class="help">JPG, PNG or WebP. The demo stores the selected image in this browser.</p><button onclick="saveSalonDetails()">Save salon details</button>`) }
  ${card(`<h2>Booking availability</h2><div class="form-grid"><label>Minimum booking notice (hours)<input id="lead-hours" type="number" min="0" max="168" value="${bookingRules(s.id).leadHours}"></label><label>Booking window (days)<input id="window-days" type="number" min="1" max="365" value="${bookingRules(s.id).windowDays}"></label><label>Confirmation<select id="confirmation-mode"><option value="manual" ${bookingRules(s.id).confirmationMode === 'manual' ? 'selected' : ''}>Manual — owner confirms</option><option value="automatic" ${bookingRules(s.id).confirmationMode === 'automatic' ? 'selected' : ''}>Automatic — confirm immediately</option></select></label><label>Cancellation / reschedule cutoff (hours)<input id="cutoff-hours" type="number" min="0" value="${cancellationCutoff(s.id)}"></label><label>Add holiday<input id="holiday-date" type="date" min="${today}"></label><label>Block date<input id="block-date" type="date" min="${today}"></label><label>Block time<select id="block-time">${times.map((time) => `<option>${time}</option>`)}</select></label></div><div class="actions"><button onclick="saveBookingRules()">Save booking rules</button><button class="ghost" onclick="addHoliday()">Add holiday</button><button class="ghost" onclick="addBlockedTime()">Block time</button></div><p class="help">${db.holidays.filter((h) => h.salonId === s.id).length} holidays · ${db.blockedTimes.filter((b) => b.salonId === s.id).length} blocked slots. These are removed from customer availability automatically.</p>`) }
  <div class="section-heading"><div><h2>Services & pricing</h2><p>Set your own price and duration for every service.</p></div><button onclick="addService()">+ Add service</button></div>
  <div class="manage-list">${services.map(serviceEditor).join('')}</div>
  <div class="section-heading"><div><h2>Staff</h2><p>Keep team details and availability up to date.</p></div><button onclick="addStaff()">+ Add staff</button></div>
  <div class="grid two">${staff.map(staffEditor).join('')}</div>`;
}
function serviceEditor(service) { return card(`<div class="editor-row"><label>Service<input id="service-name-${service.id}" value="${service.name}"></label><label>Price (₹)<input id="service-price-${service.id}" type="number" min="0" value="${service.price}"></label><label>Minutes<input id="service-duration-${service.id}" type="number" min="5" step="5" value="${service.duration}"></label><label class="toggle"><input id="service-active-${service.id}" type="checkbox" ${service.active ? 'checked' : ''}> Active</label><button onclick="saveService('${service.id}')">Save</button><button class="danger" onclick="deleteService('${service.id}')">Delete</button></div>`); }
function staffEditor(person) { return card(`<h3>${person.name}</h3><div class="form-grid"><label>Name<input id="staff-name-${person.id}" value="${person.name}"></label><label>Phone<input id="staff-phone-${person.id}" value="${person.phone || ''}" placeholder="+91"></label><label>Specialization<input id="staff-specialization-${person.id}" value="${person.specialization}"></label><label>Working hours<input id="staff-hours-${person.id}" value="${person.hours}"></label></div><label class="toggle"><input id="staff-available-${person.id}" type="checkbox" ${person.available ? 'checked' : ''}> Available for bookings</label><div class="actions"><button onclick="saveStaff('${person.id}')">Save staff</button><button class="danger" onclick="deleteStaff('${person.id}')">Remove</button></div>`); }
window.saveSalonDetails = async () => { const latitude = Number(val('salon-latitude')); const longitude = Number(val('salon-longitude')); const business = { salonName: val('salon-name').trim(), phone: val('salon-phone').trim(), address: val('salon-address').trim(), town: val('salon-location').trim(), latitude, longitude, openingHours: val('salon-hours').trim(), whatsappNumber: val('salon-whatsapp').trim(), description: val('salon-description').trim(), image: salon().image || '' }; if (!business.salonName) return alert('Enter your official salon name.'); if (!val('salon-latitude') || !val('salon-longitude')) return alert('Set the salon location on the map.'); const response = await fetch('/api/auth/salon', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(business) }); const payload = await response.json(); if (!response.ok) return alert(payload.error || 'Unable to save salon details.'); const mapped = salonFromApi(payload.salon); db.salons = db.salons.filter((item) => item.accountId !== session.accountId && item.ownerId !== session.accountId); db.salons.push(mapped); db.activeSalonId = mapped.id; render(); };
function initializeSalonLocationMap() { const element = document.getElementById('salon-location-map'); if (!element || element.dataset.ready || !window.L) return; element.dataset.ready = 'true'; const saved = [Number(element.dataset.latitude), Number(element.dataset.longitude)]; const hasSavedLocation = saved.every(Number.isFinite) && element.dataset.latitude !== '' && element.dataset.longitude !== ''; const center = hasSavedLocation ? saved : [10.7867, 76.6548]; const map = L.map(element).setView(center, hasSavedLocation ? 16 : 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map); const marker = L.marker(center, { draggable: true }).addTo(map); const select = ({ lat, lng }) => { marker.setLatLng([lat, lng]); document.getElementById('salon-latitude').value = lat.toFixed(6); document.getElementById('salon-longitude').value = lng.toFixed(6); }; map.on('click', (event) => select(event.latlng)); marker.on('dragend', () => select(marker.getLatLng())); }
window.saveBookingRules = async () => { const current = salon(); const rules = { bookingLeadTimeHours: Math.min(168, Math.max(0, Number(val('lead-hours')))), bookingWindowDays: Math.min(365, Math.max(1, Math.round(Number(val('window-days'))))), confirmationMode: val('confirmation-mode') }; const response = await fetch('/api/auth/salon', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(rules) }); const payload = await response.json(); if (!response.ok) return alert(payload.error || 'Unable to save booking rules.'); Object.assign(current, rules, { cancellationCutoffHours: Math.max(0, Number(val('cutoff-hours'))) }); save(); render(); };
window.addHoliday = () => { if (!val('holiday-date')) return; db.holidays.push({ salonId: db.activeSalonId, date: val('holiday-date') }); save(); render(); };
window.addBlockedTime = () => { if (!val('block-date')) return; db.blockedTimes.push({ salonId: db.activeSalonId, date: val('block-date'), time: val('block-time') }); save(); render(); };
window.previewSalonPhoto = (input) => { const file = input.files?.[0]; if (!file || file.size > 2 * 1024 * 1024) return alert('Choose a JPG, PNG or WebP image smaller than 2 MB.'); const reader = new FileReader(); reader.onload = () => { salon().image = reader.result; save(); document.querySelector('#photo-preview img').src = reader.result; }; reader.readAsDataURL(file); };
window.saveService = (id) => { const service = db.services.find((item) => item.id === id); Object.assign(service, { name: val(`service-name-${id}`).trim(), price: Number(val(`service-price-${id}`)), duration: Number(val(`service-duration-${id}`)), active: document.getElementById(`service-active-${id}`).checked }); save(); render(); };
window.addService = () => { db.services.unshift({ id: `service-${Date.now()}`, salonId: db.activeSalonId, name: 'New service', category: 'Beauty', price: 0, duration: 30, active: true }); save(); render(); };
window.deleteService = (id) => { if (!confirm('Delete this service?')) return; db.services = db.services.filter((item) => item.id !== id); save(); render(); };
window.saveStaff = (id) => { const person = db.staff.find((item) => item.id === id); Object.assign(person, { name: val(`staff-name-${id}`).trim(), phone: val(`staff-phone-${id}`).trim(), specialization: val(`staff-specialization-${id}`).trim(), hours: val(`staff-hours-${id}`).trim(), available: document.getElementById(`staff-available-${id}`).checked }); save(); render(); };
window.addStaff = () => { db.staff.unshift({ id: `staff-${Date.now()}`, salonId: db.activeSalonId, name: 'New staff member', phone: '', specialization: 'Beautician', hours: '9 AM - 6 PM', available: true }); save(); render(); };
window.deleteStaff = (id) => { if (!confirm('Remove this staff member?')) return; db.staff = db.staff.filter((item) => item.id !== id); save(); render(); };
function adminDashboard() { return `<h1>Admin dashboard</h1><div class="grid stats">${[['Total salons', db.salons.length], ['Active salons', db.salons.filter((s) => !s.suspended).length], ['Total customers', db.customers.length], ['Total bookings', db.bookings.length], ['Total offers', db.offers.length], ['Campaigns sent', db.campaigns.filter((c) => c.status === 'Sent').length], ['Monthly active salons', 4]].map(([a, b]) => card(`<span>${a}</span><b>${b}</b>`)).join('')}</div>`; }
function adminSalons() { return `<h1>Manage salons</h1><div class="grid three">${db.salons.map((s) => card(`<h3>${s.name}</h3><p>${s.location} • ${s.approved ? 'Approved' : 'Pending'} • ${s.suspended ? 'Suspended' : 'Active'}</p><button onclick="toggleSalon('${s.id}','approved')">${s.approved ? 'Reject' : 'Approve'}</button> <button class="ghost" onclick="toggleSalon('${s.id}','suspended')">${s.suspended ? 'Unsuspend' : 'Suspend'}</button>`)).join('')}</div>`; }
window.toggleSalon = (id, field) => { const s = db.salons.find((item) => item.id === id); s[field] = !s[field]; save(); render(); };
const adminCustomers = () => `<h1>Customers & owners</h1><div class="grid three">${db.customers.map((c) => card(`<h3>${c.name}</h3><p>${c.mobile} • ${c.location}</p><button class="${c.disabled ? '' : 'danger'}" onclick="toggleCustomer('${c.id}')">${c.disabled ? 'Enable account' : 'Disable account'}</button>`)).join('')}</div>`;
window.toggleCustomer = (id) => { const customer = db.customers.find((c) => c.id === id); customer.disabled = !customer.disabled; save(); render(); };
const adminBookings = () => `<h1>All bookings</h1>${db.bookings.slice(0, 25).map(customerBookingCard).join('')}`;
const adminCampaigns = () => `<h1>Offers & app banners</h1>${card(`<h2>Platform offer rules</h2><p>Pay-at-salon only · No misleading discounts · Salon approval required</p><label>Customer app banner<input id="admin-banner" value="${db.appBanner || 'Book trusted salons across Palakkad'}"></label><button onclick="db.appBanner=val('admin-banner');save();render()">Save banner</button>`)}<h2>Campaign report</h2><div class="grid three">${db.campaigns.map(campaignCard).join('')}</div>`;
function val(id) { return document.getElementById(id)?.value || ''; }
function text(id, value) { document.getElementById(id).textContent = value; }
function recommendedOffers() { return db.notifications.filter((n) => n.customerId === currentCustomer().id).map((n) => db.offers.find((o) => o.id === n.offerId)).filter(offerIsEligible).concat(db.offers.filter(offerIsEligible).slice(0, 5)); }
function render() { const publicRoutes = ['home', 'explore', 'salon-profile', 'book']; if (!session && !publicRoutes.includes(db.route)) db.route = 'home'; const routes = { home: customerHome, register, explore, 'salon-profile': salonProfile, book: booking, 'booking-details': bookingDetails, 'my-bookings': myBookings, 'my-offers': myOffers, profile, 'owner-dashboard': ownerDashboard, 'owner-bookings': ownerBookings, crm, offers, marketing, settings, 'admin-dashboard': adminDashboard, 'admin-salons': adminSalons, 'admin-customers': adminCustomers, 'admin-bookings': adminBookings, 'admin-campaigns': adminCampaigns }; const mobileRoutes = !session ? [['home', '⌂', 'Home'], ['explore', '⌕', 'Search']] : db.role === 'customer' ? [['home', '⌂', 'Home'], ['explore', '⌕', 'Search'], ['my-bookings', '□', 'Bookings'], ['profile', '♙', 'Profile']] : db.role === 'owner' ? [['owner-dashboard', '⌂', 'Home'], ['owner-bookings', '□', 'Bookings'], ['crm', '♙', 'Customers'], ['marketing', '◇', 'Marketing'], ['settings', '⚙', 'Setup']] : [['admin-dashboard', '⌂', 'Home'], ['admin-salons', '◇', 'Salons'], ['admin-bookings', '□', 'Bookings'], ['admin-campaigns', '↗', 'Campaigns']]; root.innerHTML = nav() + `<main>${routes[db.route]?.() || customerHome()}</main><footer>${mobileRoutes.map(([key, icon, label]) => `<button class="${db.route === key ? 'active' : ''}" onclick="navigate('${key}')"><span>${icon}</span><small>${label}</small></button>`).join('')}</footer>${authDialog()}`; if (db.route === 'settings') setTimeout(initializeSalonLocationMap, 0); if (authModal && authModal.trigger !== 'role_mismatch') setTimeout(() => initializeHomeGoogleLogin(), 0); }
render();
fetch('/api/auth/session', { cache: 'no-store' }).then((response) => response.ok ? response.json() : null).then(async (active) => { db.route = routeForPath() || 'home'; authModal = null; if (active) { const activeRole = active.activeRole === 'salon_owner' ? 'owner' : active.activeRole === 'customer' ? 'customer' : active.roles.length === 1 && active.roles.includes('salon_owner') ? 'owner' : 'customer'; session = { ...active, accountId: active.sub, role: activeRole }; db.role = session.role; await hydrateDatabase(); if (session.role === 'owner') { const ownedSalon = ensureOwnerSalon(session); db.activeSalonId = ownedSalon.id; save(); db.route = ownedSalon.name ? (routeForPath() || 'owner-dashboard') : 'settings'; history.replaceState({}, '', ownedSalon.name ? (routeForPath() === 'settings' ? '/partner/setup' : '/partner/dashboard') : '/partner/setup'); render(); } else { ensureSessionCustomer(); render(); } } else { await hydratePublicSalons(); const requestedRoute = routeForPath(); if (requestedRoute && !['home', 'explore'].includes(requestedRoute)) { const ownerRoute = requestedRoute === 'owner-dashboard' || requestedRoute === 'settings'; authModal = { trigger: 'universal', returnRoute: requestedRoute }; loginRole = ownerRoute ? 'salon_owner' : 'customer'; } render(); } }).catch(() => {});
window.addEventListener('popstate', () => { const route = routeForPath(); if (route && session) { db.route = route; render(); } });
